name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_6980"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_6060"
    type: trojan
    server: "improved-anteater.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "improved-anteater.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3639"
    type: trojan
    server: "37.49.230.24"
    port: 443
    password: "a7J9BMDPu1wuDTJ-cZoKBqvoPT9Uc7fL"
    sni: "fr.cishosts.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_7907"
    type: ss
    server: "103.133.1.38"
    port: 443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "3e96ef7d-8637-42c2-ac73-75182196e755/?ed=2560"
      host: "mfvpn.fuchen.indevs.in"
      tls: true
  - name: "@DeltaKroneckerGithub_6322"
    type: trojan
    server: "chatgpt.com"
    port: 443
    password: "Puj01Rc8UcA9IzcFcYOs8KMOhCz6aX2Q"
    sni: "mfyousheng.nl.eu.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tjwsLhx0SFASG4l9FERJ1g"
      headers:
        Host: "mfyousheng.nl.eu.org"
  - name: "@DeltaKroneckerGithub_4114"
    type: trojan
    server: "central-jawfish.rooster465.autos"
    port: 443
    password: "CF68213490"
    sni: "central-jawfish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_8487"
    type: vmess
    server: "dog-kr.kunlun01dns.com"
    port: 21004
    uuid: "9464ca40-dd75-3742-a628-d931a9f413b2"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_6984"
    type: ss
    server: "82.38.31.212"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_6090"
    type: trojan
    server: "os-tr-2.cats22.net"
    port: 443
    password: "!str18844@zxcvbn"
    sni: "os-tr-2.cats22.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_7202"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "@DeltaKroneckerGithub_2363"
    type: vless
    server: "203.137.165.164"
    port: 57554
    uuid: "980df025-74b9-4853-93e8-fb813006d7e5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d-l28t5-65-b.pbe40wmcujaw726h7cpqernzmawz4stwtrnqve0n1s5reht.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "d-l28t5-65-b.pbe40wmcujaw726h7cpqernzmawz4stwtrnqve0n1s5reht.workers.dev"
  - name: "@DeltaKroneckerGithub_669"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "455cfdc6-9abf-4e40-863f-5ff6cc63457c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "18e4d2d21241"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_6980"
      - "@DeltaKroneckerGithub_6060"
      - "@DeltaKroneckerGithub_3639"
      - "@DeltaKroneckerGithub_7907"
      - "@DeltaKroneckerGithub_6322"
      - "@DeltaKroneckerGithub_4114"
      - "@DeltaKroneckerGithub_8487"
      - "@DeltaKroneckerGithub_6984"
      - "@DeltaKroneckerGithub_6090"
      - "@DeltaKroneckerGithub_7202"
      - "@DeltaKroneckerGithub_2363"
      - "@DeltaKroneckerGithub_669"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_6980"
      - "@DeltaKroneckerGithub_6060"
      - "@DeltaKroneckerGithub_3639"
      - "@DeltaKroneckerGithub_7907"
      - "@DeltaKroneckerGithub_6322"
      - "@DeltaKroneckerGithub_4114"
      - "@DeltaKroneckerGithub_8487"
      - "@DeltaKroneckerGithub_6984"
      - "@DeltaKroneckerGithub_6090"
      - "@DeltaKroneckerGithub_7202"
      - "@DeltaKroneckerGithub_2363"
      - "@DeltaKroneckerGithub_669"

rules:
  - MATCH,PROXY
