name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_5892"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "qtkdr8jxe3wefxjm.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "qtkdr8jxe3wefxjm.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_5895"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "qtkdr8jxe3wefxjm.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_5915"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b2ba4a73-3123-479e-aa96-5973a9ecd0c0"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jmp1.907737.xyz"
    network: ws
    ws-opts:
      path: "/b2ba4a73-3123-479e-aa96-5973a9ecd0c0-vm"
      headers:
        Host: "jmp1.907737.xyz"
  - name: "@DeltaKroneckerGithub_5936"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vah4urdzl3jdx5r2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_5979"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "XEXEVIL"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/tel=@user_xexevil"
  - name: "@DeltaKroneckerGithub_5988"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "6a89a215-22bf-4bd7-9642-b95b2e09583a"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/hls/cctv5phd.m3u8"
      headers:
        Host: "guanwang.awsno.com"
  - name: "@DeltaKroneckerGithub_6006"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vah4urdzl3jdx5r2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_6028"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "NYcQg19zkwaCPM1B.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6030"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "i2psm3knof5qjjix.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6046"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "nycqg19zkwacpm1b.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6049"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "845e6b08-2919-4290-ade0-5dc7dcea59ca"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki"
  - name: "@DeltaKroneckerGithub_6091"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "93ucrn4i0pffuabk.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "93ucrn4i0pffuabk.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6116"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "6jdvarazgu3qqr6q.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6jdvarazgu3qqr6q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6123"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "qtkdr8jxe3wefxjm.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_6183"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "EX1oGt73NzPQKAc2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "EX1oGt73NzPQKAc2.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6220"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "93ucrn4i0pffuabk.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "93ucrn4i0PffUAbk.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6223"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server1.9966338.xyz"
    network: ws
    ws-opts:
      path: "/efrsdioy98wert"
      headers:
        Host: "server1.9966338.xyz"
  - name: "@DeltaKroneckerGithub_6243"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f836c736-87fc-4fde-aabc-00857ecdff3e"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_6245"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "viber.com"
  - name: "@DeltaKroneckerGithub_6263"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "9db4c708-aef8-4359-821b-38e47990be0d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_6306"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "2b9hwY8oCx7Q74NM.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6323"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nycqg19zkwacpm1b.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "nycqg19zkwacpm1b.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6350"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "1281acca-f21d-475c-bf04-eccbee7f8df2"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess-ws"
  - name: "@DeltaKroneckerGithub_6352"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "11c3627f-31e8-4695-dfbd-34076e2f1f5d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
      headers:
        Host: "None"
  - name: "@DeltaKroneckerGithub_6357"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server11.9966338.xyz"
    network: ws
    ws-opts:
      path: "/ieusrdgfhteuirgfiuws?ed=2560"
      headers:
        Host: "server11.9966338.xyz"
  - name: "@DeltaKroneckerGithub_6360"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc"
  - name: "@DeltaKroneckerGithub_6367"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server22.9966338.xyz"
    network: ws
    ws-opts:
      path: "/serhrdftshg"
      headers:
        Host: "server22.9966338.xyz"
  - name: "@DeltaKroneckerGithub_6382"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "05b8c783-7f59-47f9-9923-06a465679f6a"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
  - name: "@DeltaKroneckerGithub_6384"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "fde10e39-48bb-4dcf-b3ba-71d711323a54"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_6398"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "2b9hwy8ocx7q74nm.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "2b9hwY8oCx7Q74NM.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6403"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "ac251237-576f-40c8-a543-554960c958b1"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.sfacg.uk"
    network: ws
    ws-opts:
      path: "/or3"
      headers:
        Host: "or3.sfacg.uk"
  - name: "@DeltaKroneckerGithub_6407"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "10029c03-5d2f-4185-aab2-cbf91eef7361"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/d3d3LmlyYW5ob3N0LmNvbQ==?ed=2560"
      headers:
        Host: "https.http.www.net.com.ramseyv2.ir."
  - name: "@DeltaKroneckerGithub_6440"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "ac251237-576f-40c8-a543-554960c958b1"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "or.521166.xyz"
    network: ws
    ws-opts:
      path: "/or3"
  - name: "@DeltaKroneckerGithub_6445"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5155860e-d07d-46c3-9128-3afbd84626c7"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_6450"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "e5e563fb-cf72-4250-bfff-fa0385301061"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "google.whatsapp.snapp.torob.basalam.fortresshost.ir."
  - name: "@DeltaKroneckerGithub_6452"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "6JDvArazgU3qQR6Q.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6JDvArazgU3qQR6Q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6460"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vah4urdzl3jdx5r2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "VAH4URdZL3jDX5r2.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6462"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "NYcQg19zkwaCPM1B.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "NYcQg19zkwaCPM1B.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_6469"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server4.9966338.xyz"
    network: ws
    ws-opts:
      path: "/androirfdsreoightrjh?ed=2560"
      headers:
        Host: "server4.9966338.xyz"
  - name: "@DeltaKroneckerGithub_6471"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server15.9966338.xyz"
    network: ws
    ws-opts:
      path: "/asivewritten?ed=2560"
      headers:
        Host: "server15.9966338.xyz"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_5892"
      - "@DeltaKroneckerGithub_5895"
      - "@DeltaKroneckerGithub_5915"
      - "@DeltaKroneckerGithub_5936"
      - "@DeltaKroneckerGithub_5979"
      - "@DeltaKroneckerGithub_5988"
      - "@DeltaKroneckerGithub_6006"
      - "@DeltaKroneckerGithub_6028"
      - "@DeltaKroneckerGithub_6030"
      - "@DeltaKroneckerGithub_6046"
      - "@DeltaKroneckerGithub_6049"
      - "@DeltaKroneckerGithub_6091"
      - "@DeltaKroneckerGithub_6116"
      - "@DeltaKroneckerGithub_6123"
      - "@DeltaKroneckerGithub_6183"
      - "@DeltaKroneckerGithub_6220"
      - "@DeltaKroneckerGithub_6223"
      - "@DeltaKroneckerGithub_6243"
      - "@DeltaKroneckerGithub_6245"
      - "@DeltaKroneckerGithub_6263"
      - "@DeltaKroneckerGithub_6306"
      - "@DeltaKroneckerGithub_6323"
      - "@DeltaKroneckerGithub_6350"
      - "@DeltaKroneckerGithub_6352"
      - "@DeltaKroneckerGithub_6357"
      - "@DeltaKroneckerGithub_6360"
      - "@DeltaKroneckerGithub_6367"
      - "@DeltaKroneckerGithub_6382"
      - "@DeltaKroneckerGithub_6384"
      - "@DeltaKroneckerGithub_6398"
      - "@DeltaKroneckerGithub_6403"
      - "@DeltaKroneckerGithub_6407"
      - "@DeltaKroneckerGithub_6440"
      - "@DeltaKroneckerGithub_6445"
      - "@DeltaKroneckerGithub_6450"
      - "@DeltaKroneckerGithub_6452"
      - "@DeltaKroneckerGithub_6460"
      - "@DeltaKroneckerGithub_6462"
      - "@DeltaKroneckerGithub_6469"
      - "@DeltaKroneckerGithub_6471"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_5892"
      - "@DeltaKroneckerGithub_5895"
      - "@DeltaKroneckerGithub_5915"
      - "@DeltaKroneckerGithub_5936"
      - "@DeltaKroneckerGithub_5979"
      - "@DeltaKroneckerGithub_5988"
      - "@DeltaKroneckerGithub_6006"
      - "@DeltaKroneckerGithub_6028"
      - "@DeltaKroneckerGithub_6030"
      - "@DeltaKroneckerGithub_6046"
      - "@DeltaKroneckerGithub_6049"
      - "@DeltaKroneckerGithub_6091"
      - "@DeltaKroneckerGithub_6116"
      - "@DeltaKroneckerGithub_6123"
      - "@DeltaKroneckerGithub_6183"
      - "@DeltaKroneckerGithub_6220"
      - "@DeltaKroneckerGithub_6223"
      - "@DeltaKroneckerGithub_6243"
      - "@DeltaKroneckerGithub_6245"
      - "@DeltaKroneckerGithub_6263"
      - "@DeltaKroneckerGithub_6306"
      - "@DeltaKroneckerGithub_6323"
      - "@DeltaKroneckerGithub_6350"
      - "@DeltaKroneckerGithub_6352"
      - "@DeltaKroneckerGithub_6357"
      - "@DeltaKroneckerGithub_6360"
      - "@DeltaKroneckerGithub_6367"
      - "@DeltaKroneckerGithub_6382"
      - "@DeltaKroneckerGithub_6384"
      - "@DeltaKroneckerGithub_6398"
      - "@DeltaKroneckerGithub_6403"
      - "@DeltaKroneckerGithub_6407"
      - "@DeltaKroneckerGithub_6440"
      - "@DeltaKroneckerGithub_6445"
      - "@DeltaKroneckerGithub_6450"
      - "@DeltaKroneckerGithub_6452"
      - "@DeltaKroneckerGithub_6460"
      - "@DeltaKroneckerGithub_6462"
      - "@DeltaKroneckerGithub_6469"
      - "@DeltaKroneckerGithub_6471"

rules:
  - MATCH,PROXY
