name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_7970"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "ac251237-576f-40c8-a543-554960c958b1"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "or.521166.xyz"
    network: ws
    ws-opts:
      path: "/or3"
  - name: "@DeltaKroneckerGithub_7986"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nycqg19zkwacpm1b.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "nycqg19zkwacpm1b.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_7990"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "6a89a215-22bf-4bd7-9642-b95b2e09583a"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nomino.11hi8itbaf.workers.dev"
    network: ws
    ws-opts:
      path: "/guanwang.awsno.com/hls/cctv5phd.m3u8"
      headers:
        Host: "nomino.11hi8itbaf.workers.dev"
  - name: "@DeltaKroneckerGithub_8003"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b9de1bc9-baa7-41ac-86f7-ccd59695cb21"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki"
  - name: "@DeltaKroneckerGithub_8016"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "11c3627f-31e8-4695-dfbd-34076e2f1f5d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
      headers:
        Host: "None"
  - name: "@DeltaKroneckerGithub_8039"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "05b8c783-7f59-47f9-9923-06a465679f6a"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
  - name: "@DeltaKroneckerGithub_8045"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "93ucrn4i0pffuabk.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "93ucrn4i0PffUAbk.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8062"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "EX1oGt73NzPQKAc2.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "EX1oGt73NzPQKAc2.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8080"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5155860e-d07d-46c3-9128-3afbd84626c7"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_8083"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "b2ba4a73-3123-479e-aa96-5973a9ecd0c0"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jmp1.907737.xyz"
    network: ws
    ws-opts:
      path: "/b2ba4a73-3123-479e-aa96-5973a9ecd0c0-vm"
      headers:
        Host: "jmp1.907737.xyz"
  - name: "@DeltaKroneckerGithub_8112"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "45b83519-9c4f-4052-a11b-02e017b636d4"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/arki"
  - name: "@DeltaKroneckerGithub_8123"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "lcv8v9l7OyamxxfZ.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8142"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "2b9hwY8oCx7Q74NM.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8144"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server1.9966338.xyz"
    network: ws
    ws-opts:
      path: "/efrsdioy98wert"
      headers:
        Host: "server1.9966338.xyz"
  - name: "@DeltaKroneckerGithub_8155"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427-c1f9-4373-876c-2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "nycqg19zkwacpm1b.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8170"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "ac251237-576f-40c8-a543-554960c958b1"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "or.521166.xyz"
    network: ws
    ws-opts:
      path: "/or3"
  - name: "@DeltaKroneckerGithub_8204"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "e5e563fb-cf72-4250-bfff-fa0385301061"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "google.whatsapp.snapp.torob.basalam.fortresshost.ir."
  - name: "@DeltaKroneckerGithub_8232"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "fde10e39-48bb-4dcf-b3ba-71d711323a54"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_8248"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "fde10e39-48bb-4dcf-b3ba-71d711323a54"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_8261"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc"
  - name: "@DeltaKroneckerGithub_8267"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/ws-vmess"
      headers:
        Host: "6JDvArazgU3qQR6Q.v.3dns.vip"
  - name: "@DeltaKroneckerGithub_8302"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f836c736-87fc-4fde-aabc-00857ecdff3e"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/cctv13.m3u8"
  - name: "@DeltaKroneckerGithub_8313"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server15.9966338.xyz"
    network: ws
    ws-opts:
      path: "/asivewritten?ed=2560"
      headers:
        Host: "server15.9966338.xyz"
  - name: "@DeltaKroneckerGithub_8321"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "ac251237-576f-40c8-a543-554960c958b1"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.sfacg.uk"
    network: ws
    ws-opts:
      path: "/or3"
      headers:
        Host: "or3.sfacg.uk"
  - name: "@DeltaKroneckerGithub_8382"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "5504eaa8-1395-402f-8e0e-75ecd762e627"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "server11.9966338.xyz"
    network: ws
    ws-opts:
      path: "/ieusrdgfhteuirgfiuws?ed=2560"
      headers:
        Host: "server11.9966338.xyz"
  - name: "@DeltaKroneckerGithub_8404"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f23bb427c1f94373876c2f43e9f790f3"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "i2psm3knof5qjjix.v.3dns.vip"
    network: ws
    ws-opts:
      path: "/ws-vmess"
  - name: "@DeltaKroneckerGithub_8417"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "XEXEVIL"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/tel=@user_xexevil"
  - name: "@DeltaKroneckerGithub_8463"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "6a89a215-22bf-4bd7-9642-b95b2e09583a"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/hls/cctv5phd.m3u8"
      headers:
        Host: "guanwang.awsno.com"
  - name: "@DeltaKroneckerGithub_8498"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a25cbf11-2908-4a1b-a3a8-9a571777dca3"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "google.com"
  - name: "@DeltaKroneckerGithub_8502"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "9db4c708-aef8-4359-821b-38e47990be0d"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_8533"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "10029c03-5d2f-4185-aab2-cbf91eef7361"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/d3d3LmlyYW5ob3N0LmNvbQ==?ed=2560"
      headers:
        Host: "https.http.www.net.com.ramseyv2.ir."
  - name: "@DeltaKroneckerGithub_8535"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "1281acca-f21d-475c-bf04-eccbee7f8df2"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess-ws"
  - name: "@DeltaKroneckerGithub_8539"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "viber.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_7970"
      - "@DeltaKroneckerGithub_7986"
      - "@DeltaKroneckerGithub_7990"
      - "@DeltaKroneckerGithub_8003"
      - "@DeltaKroneckerGithub_8016"
      - "@DeltaKroneckerGithub_8039"
      - "@DeltaKroneckerGithub_8045"
      - "@DeltaKroneckerGithub_8062"
      - "@DeltaKroneckerGithub_8080"
      - "@DeltaKroneckerGithub_8083"
      - "@DeltaKroneckerGithub_8112"
      - "@DeltaKroneckerGithub_8123"
      - "@DeltaKroneckerGithub_8142"
      - "@DeltaKroneckerGithub_8144"
      - "@DeltaKroneckerGithub_8155"
      - "@DeltaKroneckerGithub_8170"
      - "@DeltaKroneckerGithub_8204"
      - "@DeltaKroneckerGithub_8232"
      - "@DeltaKroneckerGithub_8248"
      - "@DeltaKroneckerGithub_8261"
      - "@DeltaKroneckerGithub_8267"
      - "@DeltaKroneckerGithub_8302"
      - "@DeltaKroneckerGithub_8313"
      - "@DeltaKroneckerGithub_8321"
      - "@DeltaKroneckerGithub_8382"
      - "@DeltaKroneckerGithub_8404"
      - "@DeltaKroneckerGithub_8417"
      - "@DeltaKroneckerGithub_8463"
      - "@DeltaKroneckerGithub_8498"
      - "@DeltaKroneckerGithub_8502"
      - "@DeltaKroneckerGithub_8533"
      - "@DeltaKroneckerGithub_8535"
      - "@DeltaKroneckerGithub_8539"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_7970"
      - "@DeltaKroneckerGithub_7986"
      - "@DeltaKroneckerGithub_7990"
      - "@DeltaKroneckerGithub_8003"
      - "@DeltaKroneckerGithub_8016"
      - "@DeltaKroneckerGithub_8039"
      - "@DeltaKroneckerGithub_8045"
      - "@DeltaKroneckerGithub_8062"
      - "@DeltaKroneckerGithub_8080"
      - "@DeltaKroneckerGithub_8083"
      - "@DeltaKroneckerGithub_8112"
      - "@DeltaKroneckerGithub_8123"
      - "@DeltaKroneckerGithub_8142"
      - "@DeltaKroneckerGithub_8144"
      - "@DeltaKroneckerGithub_8155"
      - "@DeltaKroneckerGithub_8170"
      - "@DeltaKroneckerGithub_8204"
      - "@DeltaKroneckerGithub_8232"
      - "@DeltaKroneckerGithub_8248"
      - "@DeltaKroneckerGithub_8261"
      - "@DeltaKroneckerGithub_8267"
      - "@DeltaKroneckerGithub_8302"
      - "@DeltaKroneckerGithub_8313"
      - "@DeltaKroneckerGithub_8321"
      - "@DeltaKroneckerGithub_8382"
      - "@DeltaKroneckerGithub_8404"
      - "@DeltaKroneckerGithub_8417"
      - "@DeltaKroneckerGithub_8463"
      - "@DeltaKroneckerGithub_8498"
      - "@DeltaKroneckerGithub_8502"
      - "@DeltaKroneckerGithub_8533"
      - "@DeltaKroneckerGithub_8535"
      - "@DeltaKroneckerGithub_8539"

rules:
  - MATCH,PROXY
