name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "@DeltaKroneckerGithub_131"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "63647ea3-a88a-4161-941f-41eddb464f28"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "7nnoiou0z.3xn99hzq2sh7iekktpkeq7rofs3qc8iohrqs4pb9p.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "7nnoiou0z.3xn99hzq2sh7iekktpkeq7rofs3qc8iohrqs4pb9p.workers.dev"
  - name: "@DeltaKroneckerGithub_80"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4e4f1f70-5e56-4a76-bb9d-db087f4690c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jp3.yohototo.top"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/tyxyws"
      headers:
        Host: "jp3.yohototo.top"
  - name: "@DeltaKroneckerGithub_21"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4e4f1f70-5e56-4a76-bb9d-db087f4690c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jp3.yohototo.top"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/tyxyws"
      headers:
        Host: "jp3.yohototo.top"
  - name: "@DeltaKroneckerGithub_1261"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "489f1717-d3c7-4940-ad68-bdbdbab857f4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "x.m-90.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "t.me/TEAMNETGRATISCOL"
      headers:
        Host: "x.m-90.xyz"
  - name: "@DeltaKroneckerGithub_1110"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@DeltaKroneckerGithub_1237"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "ba9ba1d3-19c8-4792-9d3f-ddd2cdcc2e65"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "primelinelk.me"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/xprolk-primeline"
      headers:
        Host: "primelinelk.me"
  - name: "@DeltaKroneckerGithub_4183"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
  - name: "@DeltaKroneckerGithub_3206"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.volumeroot.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.volumeroot.com"
  - name: "@DeltaKroneckerGithub_191"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "@DeltaKroneckerGithub_1049"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "44d636ef-7056-4bdf-a3f4-acabe2adfc6f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zme2.3ka.hhll.vavava.kdns.fr"
    network: ws
    ws-opts:
      path: "/?auto=1"
      headers:
        Host: "zme2.3ka.hhll.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_295"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3f87daa8-3af8-40a0-b655-127911e008dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "7nnoiou0z.3xn99hzq2sh7iekktpkeq7rofs3qc8iohrqs4pb9p.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "7nnoiou0z.3xn99hzq2sh7iekktpkeq7rofs3qc8iohrqs4pb9p.workers.dev"
  - name: "@DeltaKroneckerGithub_201"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6c713691-3ca2-4446-ad25-113d1bed6b03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fdghyt.com"
    network: ws
    ws-opts:
      path: "/vpn-wss/fluxor/59011/"
      headers:
        Host: "fdghyt.com"
  - name: "@DeltaKroneckerGithub_423"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "48572af1-d091-457b-a86e-4a457e99927f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3h-unitedstates3.09vpn.com"
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "3h-unitedstates3.09vpn.com"
  - name: "@DeltaKroneckerGithub_1837"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_284"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d342d11e-d224-4463-b982-532309285094"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ccc.010304.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "ccc.010304.xyz"
  - name: "@DeltaKroneckerGithub_973"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "26769ac3-b34c-430a-87f8-e1de14619d25"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.blueknightnet.qzz.io"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@BlueKnight_net--@BlueKnight_net--@BlueKnight_net--@BlueKnight_net--@BlueKnight_net--@BlueKnight_net"
      headers:
        Host: "uwu.blueknightnet.qzz.io"
  - name: "@DeltaKroneckerGithub_6245"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "567f4be5-12ab-42e1-b8d9-db6fd1fdd31c"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/vmess/"
      headers:
        Host: "viber.com"
  - name: "@DeltaKroneckerGithub_2664"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1291"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3c52e091-6714-4915-949f-2149fe69951b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray.simspeedup.com"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "v2ray.simspeedup.com"
  - name: "@DeltaKroneckerGithub_782"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4e4f1f70-5e56-4a76-bb9d-db087f4690c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jp3.yohototo.top"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/tyxyws"
      headers:
        Host: "jp3.yohototo.top"
  - name: "@DeltaKroneckerGithub_1239"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "XpnTeam-4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ssl.fastly.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "Appxdn.global.ssl.fastly.net"
  - name: "@DeltaKroneckerGithub_751"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "26769ac3-b34c-430a-87f8-e1de14619d25"
    udp: true
    network: ws
    ws-opts:
      path: "/@BlueKnight_net--@BlueKnight_net"
      headers:
        Host: "uwu.blueknightnet.qzz.io"
  - name: "@DeltaKroneckerGithub_554"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a853e120-3570-462b-aec1-e8f3d4f92d24"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "asia.csmaster.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "asia.csmaster.site"
  - name: "@DeltaKroneckerGithub_414"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e3fb01b6-69b4-41d7-babf-696d992de194"
    udp: true
    network: ws
    ws-opts:
      path: "/@BlueKnight_net--@BlueKnight_net"
      headers:
        Host: "uwu.blueknightnet.qzz.io"
  - name: "@DeltaKroneckerGithub_771"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "25f86cb1-2140-4085-abcb-c3a0ea7a4be0"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "OV-France1.09vpn.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_131"
      - "@DeltaKroneckerGithub_80"
      - "@DeltaKroneckerGithub_21"
      - "@DeltaKroneckerGithub_1261"
      - "@DeltaKroneckerGithub_1110"
      - "@DeltaKroneckerGithub_1237"
      - "@DeltaKroneckerGithub_4183"
      - "@DeltaKroneckerGithub_3206"
      - "@DeltaKroneckerGithub_191"
      - "@DeltaKroneckerGithub_1049"
      - "@DeltaKroneckerGithub_295"
      - "@DeltaKroneckerGithub_201"
      - "@DeltaKroneckerGithub_423"
      - "@DeltaKroneckerGithub_1837"
      - "@DeltaKroneckerGithub_284"
      - "@DeltaKroneckerGithub_973"
      - "@DeltaKroneckerGithub_6245"
      - "@DeltaKroneckerGithub_2664"
      - "@DeltaKroneckerGithub_1291"
      - "@DeltaKroneckerGithub_782"
      - "@DeltaKroneckerGithub_1239"
      - "@DeltaKroneckerGithub_751"
      - "@DeltaKroneckerGithub_554"
      - "@DeltaKroneckerGithub_414"
      - "@DeltaKroneckerGithub_771"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "@DeltaKroneckerGithub_131"
      - "@DeltaKroneckerGithub_80"
      - "@DeltaKroneckerGithub_21"
      - "@DeltaKroneckerGithub_1261"
      - "@DeltaKroneckerGithub_1110"
      - "@DeltaKroneckerGithub_1237"
      - "@DeltaKroneckerGithub_4183"
      - "@DeltaKroneckerGithub_3206"
      - "@DeltaKroneckerGithub_191"
      - "@DeltaKroneckerGithub_1049"
      - "@DeltaKroneckerGithub_295"
      - "@DeltaKroneckerGithub_201"
      - "@DeltaKroneckerGithub_423"
      - "@DeltaKroneckerGithub_1837"
      - "@DeltaKroneckerGithub_284"
      - "@DeltaKroneckerGithub_973"
      - "@DeltaKroneckerGithub_6245"
      - "@DeltaKroneckerGithub_2664"
      - "@DeltaKroneckerGithub_1291"
      - "@DeltaKroneckerGithub_782"
      - "@DeltaKroneckerGithub_1239"
      - "@DeltaKroneckerGithub_751"
      - "@DeltaKroneckerGithub_554"
      - "@DeltaKroneckerGithub_414"
      - "@DeltaKroneckerGithub_771"

rules:
  - MATCH,PROXY
