name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇧🇪_1"
    type: vless
    server: "113.30.152.2"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "be-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cceRo0o9bFMlCNVahZCrQWRzMAsR5M6abWXADIapY0w"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_2"
    type: vless
    server: "45.148.103.85"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ca-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇪_1"
      - "🇧🇪_2"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇧🇪_1"
      - "🇧🇪_2"

rules:
  - MATCH,PROXY
