name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇨🇦_1"
    type: vless
    server: "178.83.46.91"
    port: 8080
    uuid: "6bceb548-d9b6-461f-8e37-a5a7fbcdc2c8"
    udp: true
  - name: "🇨🇦_2"
    type: vless
    server: "209.200.246.61"
    port: 443
    uuid: "ab9929fd-ab22-48e3-8723-480733c0eca9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ca.vpnskyline.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "NO3w10fOUvwK8L7vzCVPDLWIKYCHDaB6ealdMnv4jS4"
      short-id: "e287e3906e3c"
    flow: "xtls-rprx-vision"
  - name: "🇨🇦_3"
    type: vless
    server: "185.218.17.127"
    port: 443
    uuid: "bc8446e7-ba8e-4dfd-92df-8681793fe31e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "corporate.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QKaBb_u0KoNkMYbh9ljrxC9BDtnHyFoaMd4-s4xfKxQ"
      short-id: "33c0b6e213"
    flow: "xtls-rprx-vision"
  - name: "🇨🇦_4"
    type: vless
    server: "209.200.246.148"
    port: 443
    uuid: "ca52e2b6-fb9f-4dac-b6dc-49da9923f251"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "uTmb-ytXsx8p0fkBz7A76SHpWk7_oVutIA4LGTE8BQk"
      short-id: "f98843107912e782"
    flow: "xtls-rprx-vision"
  - name: "🇨🇦_5"
    type: vless
    server: "212.74.39.188"
    port: 8080
    uuid: "6bceb548-d9b6-461f-8e37-a5a7fbcdc2c8"
    udp: true
  - name: "🇨🇦_6"
    type: vless
    server: "194.77.220.104"
    port: 8080
    uuid: "6bceb548-d9b6-461f-8e37-a5a7fbcdc2c8"
    udp: true
  - name: "🇨🇦_7"
    type: vless
    server: "168.222.43.200"
    port: 8080
    uuid: "6bceb548-d9b6-461f-8e37-a5a7fbcdc2c8"
    udp: true
  - name: "🇨🇦_8"
    type: vless
    server: "milo.rubinaz.xyz"
    port: 8080
    uuid: "6bceb548-d9b6-461f-8e37-a5a7fbcdc2c8"
    udp: true
  - name: "🇨🇦_9"
    type: vless
    server: "66.70.179.198"
    port: 2053
    uuid: "dc620cd6-a9d8-4a0f-8f18-006b895db77e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    reality-opts:
      public-key: "k4l6TxwkBbx9DhZAFpByq5rfCWFSgyOex3f_eFe9CWU"
      short-id: "83f8317a948bb769"
  - name: "🇨🇦_10"
    type: trojan
    server: "159.203.22.227"
    port: 443
    password: "acfef609-b3c7-4e52-b292-8921d5fca90d"
    sni: "ca-full.privateip.net"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇦_11"
    type: trojan
    server: "216.144.231.47"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇦_12"
    type: trojan
    server: "35.183.238.42"
    port: 443
    password: "your_password"
    sni: "aws-ca-central-1.f1rocketnode.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇦_13"
    type: trojan
    server: "51.222.15.68"
    port: 443
    password: "f4dc01c0-6376-11ee-8ca8-1239d0255272"
    sni: "www.ewane.krd"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇦_14"
    type: trojan
    server: "216.128.184.4"
    port: 443
    password: "qr5nXh3P7K6T"
    sni: "ash.d22e0961-e0a7-49b8-8259-eac71e24d27b.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇨🇦_15"
    type: ss
    server: "64.74.163.69"
    port: 18766
    cipher: "aes-128-gcm"
    password: "4efe1af272e7292139b889f6a63ee071"
    udp: true
  - name: "🇨🇦_16"
    type: ss
    server: "64.74.161.149"
    port: 17202
    cipher: "aes-128-gcm"
    password: "1cbb3e347ee86e1980a7c731e9dd00a0"
    udp: true
  - name: "🇨🇦_17"
    type: ss
    server: "51.222.107.43"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:HWFFJN19JkvbTKo/79AfnbRBK9uHUUaFNZJyLjEoJGs="
    udp: true
  - name: "🇨🇦_18"
    type: ss
    server: "51.222.200.165"
    port: 5000
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇨🇦_19"
    type: ss
    server: "51.222.155.113"
    port: 5601
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇨🇦_20"
    type: ss
    server: "51.222.107.43"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:HWFFJN19JkvbTKo/79AfnbRBK9uHUUaFNZJyLjEoJGs="
    udp: true
  - name: "🇨🇦_21"
    type: ss
    server: "51.222.141.125"
    port: 445
    cipher: "aes-256-gcm"
    password: "zDNVedRFPQexG9v"
    udp: true
  - name: "🇨🇦_22"
    type: ss
    server: "51.79.64.198"
    port: 8119
    cipher: "aes-256-gcm"
    password: "cdBIDV42DCwnfIN"
    udp: true
  - name: "🇨🇦_23"
    type: ss
    server: "51.222.200.165"
    port: 5000
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇨🇦_24"
    type: ss
    server: "51.222.200.165"
    port: 5000
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇨🇦_25"
    type: ss
    server: "51.222.12.127"
    port: 445
    cipher: "aes-256-gcm"
    password: "zDNVedRFPQexG9v"
    udp: true
  - name: "🇨🇦_26"
    type: ss
    server: "51.79.49.116"
    port: 8882
    cipher: "aes-256-gcm"
    password: "kDWvXYZoTBcGkC4"
    udp: true
  - name: "🇨🇦_27"
    type: ss
    server: "51.79.49.116"
    port: 8882
    cipher: "aes-256-gcm"
    password: "kDWvXYZoTBcGkC4"
    udp: true
  - name: "🇨🇦_28"
    type: ss
    server: "51.222.136.236"
    port: 8882
    cipher: "aes-256-gcm"
    password: "kDWvXYZoTBcGkC4"
    udp: true
  - name: "🇨🇦_29"
    type: ss
    server: "64.74.161.147"
    port: 17200
    cipher: "aes-128-gcm"
    password: "1cbb3e347ee86e1980a7c731e9dd00a0"
    udp: true
  - name: "🇨🇦_30"
    type: ss
    server: "64.74.161.147"
    port: 17200
    cipher: "aes-128-gcm"
    password: "1cbb3e347ee86e1980a7c731e9dd00a0"
    udp: true
  - name: "🇨🇦_31"
    type: ss
    server: "51.79.85.185"
    port: 8118
    cipher: "aes-256-gcm"
    password: "cdBIDV42DCwnfIN"
    udp: true
  - name: "🇨🇦_32"
    type: ss
    server: "51.222.155.32"
    port: 5003
    cipher: "aes-256-gcm"
    password: "g5MeD6Ft3CWlJId"
    udp: true
  - name: "🇨🇦_33"
    type: ss
    server: "51.222.155.113"
    port: 5601
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇨🇦_34"
    type: ss
    server: "64.74.163.69"
    port: 18766
    cipher: "aes-128-gcm"
    password: "4efe1af272e7292139b889f6a63ee071"
    udp: true
  - name: "🇨🇦_35"
    type: vmess
    server: "23.162.200.198"
    port: 18000
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "🇨🇦_36"
    type: vmess
    server: "134.195.196.211"
    port: 18000
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇦_1"
      - "🇨🇦_2"
      - "🇨🇦_3"
      - "🇨🇦_4"
      - "🇨🇦_5"
      - "🇨🇦_6"
      - "🇨🇦_7"
      - "🇨🇦_8"
      - "🇨🇦_9"
      - "🇨🇦_10"
      - "🇨🇦_11"
      - "🇨🇦_12"
      - "🇨🇦_13"
      - "🇨🇦_14"
      - "🇨🇦_15"
      - "🇨🇦_16"
      - "🇨🇦_17"
      - "🇨🇦_18"
      - "🇨🇦_19"
      - "🇨🇦_20"
      - "🇨🇦_21"
      - "🇨🇦_22"
      - "🇨🇦_23"
      - "🇨🇦_24"
      - "🇨🇦_25"
      - "🇨🇦_26"
      - "🇨🇦_27"
      - "🇨🇦_28"
      - "🇨🇦_29"
      - "🇨🇦_30"
      - "🇨🇦_31"
      - "🇨🇦_32"
      - "🇨🇦_33"
      - "🇨🇦_34"
      - "🇨🇦_35"
      - "🇨🇦_36"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇨🇦_1"
      - "🇨🇦_2"
      - "🇨🇦_3"
      - "🇨🇦_4"
      - "🇨🇦_5"
      - "🇨🇦_6"
      - "🇨🇦_7"
      - "🇨🇦_8"
      - "🇨🇦_9"
      - "🇨🇦_10"
      - "🇨🇦_11"
      - "🇨🇦_12"
      - "🇨🇦_13"
      - "🇨🇦_14"
      - "🇨🇦_15"
      - "🇨🇦_16"
      - "🇨🇦_17"
      - "🇨🇦_18"
      - "🇨🇦_19"
      - "🇨🇦_20"
      - "🇨🇦_21"
      - "🇨🇦_22"
      - "🇨🇦_23"
      - "🇨🇦_24"
      - "🇨🇦_25"
      - "🇨🇦_26"
      - "🇨🇦_27"
      - "🇨🇦_28"
      - "🇨🇦_29"
      - "🇨🇦_30"
      - "🇨🇦_31"
      - "🇨🇦_32"
      - "🇨🇦_33"
      - "🇨🇦_34"
      - "🇨🇦_35"
      - "🇨🇦_36"

rules:
  - MATCH,PROXY
