name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇨🇿_1"
    type: vless
    server: "193.23.195.37"
    port: 8443
    uuid: "9ebf4fda-7395-4800-b42f-b2dda649880a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇨🇿_2"
    type: vless
    server: "31.76.7.227"
    port: 443
    uuid: "d0e771c5-024e-4393-bb90-4a3e3c561656"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "origin.vpnoodles.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "nIL5EeUo2XUkCaLJGbzgRm6zhF-96kWvV2VmhEt3CX4"
      short-id: "4af4102cb26e59"
    flow: "xtls-rprx-vision"
  - name: "🇨🇿_3"
    type: vless
    server: "gw1.edgemedia.lol"
    port: 8443
    uuid: "9ebf4fda-7395-4800-b42f-b2dda649880a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇿_1"
      - "🇨🇿_2"
      - "🇨🇿_3"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇨🇿_1"
      - "🇨🇿_2"
      - "🇨🇿_3"

rules:
  - MATCH,PROXY
