name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "95.85.242.160"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_2"
    type: vless
    server: "93.89.220.37"
    port: 443
    uuid: "185e2bb3-2934-48d0-bbd5-dd20d16e83ee"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ibm.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "lwKaUQ81wJUJRsqAPsfTPj5V_f9N50UYEwzRI_nuq2g"
      short-id: "e88cb983f3c97528"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_3"
    type: vless
    server: "45.133.151.163"
    port: 25895
    uuid: "f90b7d43-69e2-4b46-a672-8029bc6796a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "jOVKSP-bS9OkILJ8Epz8hadh6qhavCrOiJYeF0NCn0k"
      short-id: "a73f0410d728c823"
  - name: "🇪🇪_4"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "chrome"
  - name: "🇪🇪_5"
    type: vless
    server: "150.241.101.17"
    port: 8443
    uuid: "47d9b534-8a0a-4bd2-90f1-1d6ade14427e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.net"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_6"
    type: vless
    server: "stoniy.fytpn.com"
    port: 56789
    uuid: "a889fba5-5472-4022-a6b4-9710157fda2f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stoniy.fytpn.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PDHRi_RRFsPhxLoH2C1l9A9HdL2y7g1uOzXmY0XnmzQ"
      short-id: "a2aa"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_7"
    type: vless
    server: "ee.edgemedia.lol"
    port: 7443
    uuid: "8ff3db5a-5f41-4f25-a8a4-7fbf00f1c319"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_8"
    type: vless
    server: "95.85.242.81"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_9"
    type: vless
    server: "212.87.190.93"
    port: 25895
    uuid: "f90b7d43-69e2-4b46-a672-8029bc6796a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jOVKSP-bS9OkILJ8Epz8hadh6qhavCrOiJYeF0NCn0k"
      short-id: "a73f0410d728c823"
  - name: "🇪🇪_10"
    type: vless
    server: "132.243.65.86"
    port: 443
    uuid: "73705990-99fd-4deb-98b4-91ca7bf9bbc0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee2x.global-cdn.org"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "content.v1.Feed"
  - name: "🇪🇪_11"
    type: vless
    server: "95.85.242.166"
    port: 443
    uuid: "2b781b4a-5942-0018-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee-root.sworkingvpn.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_12"
    type: vless
    server: "150.241.101.80"
    port: 8443
    uuid: "47d9b534-8a0a-4bd2-90f1-1d6ade14427e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_13"
    type: trojan
    server: "ee-1.kamediorg.com"
    port: 443
    password: "GUGm7DHtpSx7SuPyUD"
    sni: "ee-1.kamediorg.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_14"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_15"
    type: trojan
    server: "45.139.194.80"
    port: 443
    password: "GUGm7DHtpSx7SuPyUD"
    sni: "45.139.194.80"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_16"
    type: trojan
    server: "ee-1.tr202604.com"
    port: 443
    password: "pjqRC5wfEFhYTyiaKF"
    sni: "ee-1.tr202604.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_17"
    type: trojan
    server: "stoniy.fytpn.com"
    port: 2097
    password: "gHncxmRjWEJ7apX5XuXsHw4kGexMH_gU"
    sni: "stoniy.fytpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_18"
    type: trojan
    server: "45.139.194.66"
    port: 443
    password: "AG4yPUSazj57DBFnKG"
    sni: "45.139.194.66"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_19"
    type: trojan
    server: "ee-1.tr202604.com"
    port: 443
    password: "AG4yPUSazj57DBFnKG"
    sni: "ee-1.tr202604.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_20"
    type: trojan
    server: "45.139.194.60"
    port: 443
    password: "pjqRC5wfEFhYTyiaKF"
    sni: "ee-1.tr202604.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_21"
    type: trojan
    server: "ee-1.kamediorg.com"
    port: 443
    password: "wQz5G4ybA9eC3BQDkd"
    sni: "ee-1.kamediorg.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"
      - "🇪🇪_15"
      - "🇪🇪_16"
      - "🇪🇪_17"
      - "🇪🇪_18"
      - "🇪🇪_19"
      - "🇪🇪_20"
      - "🇪🇪_21"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"
      - "🇪🇪_15"
      - "🇪🇪_16"
      - "🇪🇪_17"
      - "🇪🇪_18"
      - "🇪🇪_19"
      - "🇪🇪_20"
      - "🇪🇪_21"

rules:
  - MATCH,PROXY
