name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "193.23.195.37"
    port: 13443
    uuid: "9ebf4fda-7395-4800-b42f-b2dda649880a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "157.228.128.59"
    port: 443
    uuid: "df53b6c2-8005-475c-9eb9-74e1be785dc8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QnxkyscHouhaLDJHT47beyenVd4LHi62yfJIeRV01Ws"
      short-id: "06e00e7c"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_3"
    type: vless
    server: "144.31.27.215"
    port: 43000
    uuid: "47f79fc1-0646-40e8-8a58-73e85d183d5a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "144.31.27.215"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dxCQnOekn14riFxt3vdwDNydvW47FsmwFG6BJ2mUgEg"
      short-id: "568d87a47271344e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_4"
    type: vless
    server: "151.241.137.132"
    port: 443
    uuid: "5786d86f-7731-4174-b1a3-84297e54b015"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finland.ali-bard.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SB1uC0OEveYjSiS_Nuw9Ld-uVVXWqi794OGnldthY3I"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_5"
    type: vless
    server: "36a466g.fi1.h1clayd.click"
    port: 443
    uuid: "9a0e84f8-4b58-477f-99da-5fac5a2e58e8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "36a466g.fi1.h1clayd.click"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pAgrBKJCmuSJHIzYkEJTqsOBOVBK_DMtEqFPo-PaTkg"
      short-id: "b3c9d0c6bdd114a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "0adb9638509b"
  - name: "🇫🇮_6"
    type: vless
    server: "van2.ragnarok-it.xyz"
    port: 8446
    uuid: "a61496c3-f256-4a36-8a52-8638b9cc900a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amd.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "Y6ZtoxCUW1qFIvLTNfbrsyfCDoIBaRsqGNtbF_mcAXM"
      short-id: "7bac4b112d30d1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_7"
    type: vless
    server: "95.216.27.15"
    port: 2053
    uuid: "1c81f6d3-5771-4c5d-9fdd-1655eff50634"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "4nfogj5mHqNowtSn_2sXS3xTX8vcH75rFEU2BWvyekM"
      short-id: "d368b94e275ab080"
  - name: "🇫🇮_8"
    type: vless
    server: "45.133.151.188"
    port: 443
    uuid: "9a0e84f8-4b58-477f-99da-5fac5a2e58e8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "36a466g.fi1.h1clayd.click"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pAgrBKJCmuSJHIzYkEJTqsOBOVBK_DMtEqFPo-PaTkg"
      short-id: "b3c9d0c6bdd114a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "0adb9638509b"
  - name: "🇫🇮_9"
    type: vless
    server: "65.108.3.59"
    port: 443
    uuid: "8df2e661-6f46-471b-9133-7fc13a0daa35"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.eitaa.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jDoORbrtDrvAlFSo19CJbc99C4ev8SAo1MwczSUt9no"
      short-id: "90ec9bba2019"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_10"
    type: vless
    server: "185.166.154.111"
    port: 443
    uuid: "91d734be-a3d0-4d50-83ab-74cf7b6966fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.bulkavpn.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bQZcMViJWXus9rMSTOa-ZAaUJC0mIlPx7XmzrLp8GQU"
      short-id: "94f32cfc"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_11"
    type: vless
    server: "13.143.166.245"
    port: 443
    uuid: "2a0b565e-904e-4d3b-a7eb-0725d6a2c7cd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.jsdelivr.net"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "FuKGULeQ9xZMJN8hWz6J_49tDJKT9HA-nsAXOOVRmyM"
      short-id: "ff867ed245c73f43"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_12"
    type: trojan
    server: "nnnmjju.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_13"
    type: trojan
    server: "d05f4aa7-92b1-a659-e3b9-695dd2870b3c.131.pp.ua"
    port: 443
    password: "5453ae26-250d-4e79-b4ec-016baf806865"
    sni: "D05F4aA7-92B1-a659-E3b9-695Dd2870B3c.131.Pp.UA"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_14"
    type: trojan
    server: "135.181.41.169"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_15"
    type: trojan
    server: "45.12.70.200"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_16"
    type: trojan
    server: "bbbnnmj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnnmj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_17"
    type: trojan
    server: "bbbnhj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnhj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_18"
    type: trojan
    server: "vvbgh.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "vvbgh.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_19"
    type: ss
    server: "185.103.110.66"
    port: 18280
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_20"
    type: ss
    server: "185.103.110.68"
    port: 18283
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_21"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_22"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_23"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_24"
    type: ss
    server: "185.103.110.66"
    port: 18280
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_25"
    type: ss
    server: "185.103.110.68"
    port: 18283
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_26"
    type: ss
    server: "185.103.110.68"
    port: 18283
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_27"
    type: ss
    server: "45.149.114.171"
    port: 777
    cipher: "chacha20-ietf-poly1305"
    password: "Jeoq8ujfkqZKKvACQhoqBQ1PA3uq4242"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"

rules:
  - MATCH,PROXY
