name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇮_1"
    type: vless
    server: "194.87.6.192"
    port: 56789
    uuid: "a889fba5-5472-4022-a6b4-9710157fda2f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ger6.fytpn.com"
    reality-opts:
      public-key: "PDHRi_RRFsPhxLoH2C1l9A9HdL2y7g1uOzXmY0XnmzQ"
      short-id: "a2aa"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_2"
    type: vless
    server: "45.144.179.112"
    port: 443
    uuid: "86096188-0ece-41af-922d-792c5f96c3ad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru.caloribro.uno"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8cN2ldJOVJ_ulUORM3mblWMg1etGrTruJoAtYyhE5h8"
      short-id: "73cd09c320ca209d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_3"
    type: vless
    server: "193.148.56.174"
    port: 443
    uuid: "e937b92c-701f-420e-a621-3eb3b75de467"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nature.puffixhosting.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "koxjdhLHJiX8H1y12ffCfzL3XoLvgYCdv46CwY3IjiM"
      short-id: "425f681053ccf59b"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_4"
    type: vless
    server: "94.156.79.93"
    port: 443
    uuid: "1a5e7720-abf3-4b9b-bc9b-9a900a04b434"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_0fpFqEEuCso3B8K7AAcMjctwG_xfCxO2PdKzGd_-hg"
      short-id: "f129dcdbf64f"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_5"
    type: vless
    server: "151.241.137.132"
    port: 443
    uuid: "5786d86f-7731-4174-b1a3-84297e54b015"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finland.ali-bard.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SB1uC0OEveYjSiS_Nuw9Ld-uVVXWqi794OGnldthY3I"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_6"
    type: vless
    server: "45.133.151.188"
    port: 443
    uuid: "9a0e84f8-4b58-477f-99da-5fac5a2e58e8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "36a466g.fi1.h1clayd.click"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pAgrBKJCmuSJHIzYkEJTqsOBOVBK_DMtEqFPo-PaTkg"
      short-id: "b3c9d0c6bdd114a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "0adb9638509b"
  - name: "🇫🇮_7"
    type: vless
    server: "193.23.195.37"
    port: 13443
    uuid: "8ff3db5a-5f41-4f25-a8a4-7fbf00f1c319"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_8"
    type: vless
    server: "144.31.27.215"
    port: 43000
    uuid: "47f79fc1-0646-40e8-8a58-73e85d183d5a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "144.31.27.215"
    reality-opts:
      public-key: "dxCQnOekn14riFxt3vdwDNydvW47FsmwFG6BJ2mUgEg"
      short-id: "568d87a47271344e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_9"
    type: vless
    server: "185.166.154.111"
    port: 443
    uuid: "91d734be-a3d0-4d50-83ab-74cf7b6966fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.bulkavpn.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bQZcMViJWXus9rMSTOa-ZAaUJC0mIlPx7XmzrLp8GQU"
      short-id: "94f32cfc"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_10"
    type: vless
    server: "153.80.241.206"
    port: 8444
    uuid: "f55e9aba-7b14-4f6f-b59a-d5b3d45c9309"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FWitre1jinQR7qz5HQ0q2Q4Gg9xA9B0SyizCziN7Ch0"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "GunService"
  - name: "🇫🇮_11"
    type: vless
    server: "170.168.4.59"
    port: 17170
    uuid: "3eec23c1-2a0d-4d53-afa5-62745a1f5ffe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "northerntrail.gazette.help"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "trail-grpc"
  - name: "🇫🇮_12"
    type: vless
    server: "46.243.235.246"
    port: 7449
    uuid: "f23bc4f1-cc71-4003-ae6c-d6abe21d8191"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "passport.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TixECE6AqdT0DEihGXGqBAovNYMxZSB2csK0Lmm1ch0"
      short-id: "11e097a032298bd8"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_13"
    type: vless
    server: "31.76.31.170"
    port: 443
    uuid: "e937b92c-701f-420e-a621-3eb3b75de467"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "merge.puffixhosting.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SafqZ77i7oXSmS49V55JxTZOsTYykoyqZXPPI0Ck_io"
      short-id: "04b63b075469bd5d"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_14"
    type: vless
    server: "13.143.137.206"
    port: 443
    uuid: "8ff3db5a-5f41-4f25-a8a4-7fbf00f1c319"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_15"
    type: vless
    server: "ger6.fytpn.com"
    port: 56789
    uuid: "a889fba5-5472-4022-a6b4-9710157fda2f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ger6.fytpn.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PDHRi_RRFsPhxLoH2C1l9A9HdL2y7g1uOzXmY0XnmzQ"
      short-id: "a2aa"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_16"
    type: vless
    server: "31.76.31.171"
    port: 443
    uuid: "e937b92c-701f-420e-a621-3eb3b75de467"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "static.puffixhosting.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "LhfYKngRlrk97udPBbU6mcVABiLeACST-hs3aBLZVWs"
      short-id: "a4a51977d0057e2a"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_17"
    type: vless
    server: "31.76.31.172"
    port: 443
    uuid: "e937b92c-701f-420e-a621-3eb3b75de467"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "melow.puffixhosting.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "zw_9ATs5eTFhYtSyH8I0EclQfvwGYMIEoufkwai2JmQ"
      short-id: "a9057238a01487ce"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_18"
    type: vless
    server: "13.143.166.245"
    port: 443
    uuid: "2a0b565e-904e-4d3b-a7eb-0725d6a2c7cd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.jsdelivr.net"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "FuKGULeQ9xZMJN8hWz6J_49tDJKT9HA-nsAXOOVRmyM"
      short-id: "ff867ed245c73f43"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_19"
    type: vless
    server: "87.242.94.90"
    port: 8443
    uuid: "f23bc4f1-cc71-4003-ae6c-d6abe21d8191"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "passport.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pobC1laHCtpMK1EA520CyOpYeel0t90hEV_eRJExFAE"
      short-id: "20272c52657d22da"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_20"
    type: vless
    server: "65.108.3.59"
    port: 443
    uuid: "8df2e661-6f46-471b-9133-7fc13a0daa35"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.eitaa.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jDoORbrtDrvAlFSo19CJbc99C4ev8SAo1MwczSUt9no"
      short-id: "90ec9bba2019"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_21"
    type: vless
    server: "193.23.195.37"
    port: 13443
    uuid: "9ebf4fda-7395-4800-b42f-b2dda649880a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_22"
    type: vless
    server: "85.209.129.113"
    port: 2443
    uuid: "077d2648-b995-4512-a018-2d1e0f79629a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fonts.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cnmFHIiPbBDSOiui-ZJw8JIWSa4UARyNrHhBp3p7sBc"
      short-id: "f1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇫🇮_23"
    type: vless
    server: "cdn.bulkavpn.top"
    port: 443
    uuid: "91d734be-a3d0-4d50-83ab-74cf7b6966fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.bulkavpn.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bQZcMViJWXus9rMSTOa-ZAaUJC0mIlPx7XmzrLp8GQU"
      short-id: "94f32cfc"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_24"
    type: vless
    server: "gw2.edgemedia.lol"
    port: 13443
    uuid: "8ff3db5a-5f41-4f25-a8a4-7fbf00f1c319"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_25"
    type: vless
    server: "36a466g.fi1.h1clayd.click"
    port: 443
    uuid: "9a0e84f8-4b58-477f-99da-5fac5a2e58e8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "36a466g.fi1.h1clayd.click"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pAgrBKJCmuSJHIzYkEJTqsOBOVBK_DMtEqFPo-PaTkg"
      short-id: "b3c9d0c6bdd114a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "0adb9638509b"
  - name: "🇫🇮_26"
    type: vless
    server: "194.226.121.119"
    port: 2087
    uuid: "ec6f8131-7a5d-4117-9627-6fb2b39ae0da"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "sXOLkj_L8EpGL0yZA9laLDaPfpwVEcBVHLSvunPVQwA"
      short-id: "a644f94155c87551"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇮_27"
    type: vless
    server: "87.228.92.114"
    port: 25481
    uuid: "68c3d665-b2b5-4ffb-9f37-9f3d8c47324d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mhIAHuZIEr2NpdGGSeOxar7VRSgEfVoNwb_G8Y0073E"
      short-id: "3b84fc70657725af"
    network: grpc
    grpc-opts:
      grpc-service-name: "8cb5baa18cd7"
  - name: "🇫🇮_28"
    type: vless
    server: "13.143.137.206"
    port: 13443
    uuid: "8ff3db5a-5f41-4f25-a8a4-7fbf00f1c319"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_29"
    type: vless
    server: "van2.ragnarok-it.xyz"
    port: 8446
    uuid: "a61496c3-f256-4a36-8a52-8638b9cc900a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amd.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "Y6ZtoxCUW1qFIvLTNfbrsyfCDoIBaRsqGNtbF_mcAXM"
      short-id: "7bac4b112d30d1"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_30"
    type: vless
    server: "157.228.128.59"
    port: 443
    uuid: "df53b6c2-8005-475c-9eb9-74e1be785dc8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QnxkyscHouhaLDJHT47beyenVd4LHi62yfJIeRV01Ws"
      short-id: "06e00e7c"
    flow: "xtls-rprx-vision"
  - name: "🇫🇮_31"
    type: trojan
    server: "d05f4aa7-92b1-a659-e3b9-695dd2870b3c.131.pp.ua"
    port: 443
    password: "5453ae26-250d-4e79-b4ec-016baf806865"
    sni: "D05F4aA7-92B1-a659-E3b9-695Dd2870B3c.131.Pp.UA"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_32"
    type: trojan
    server: "45.12.70.200"
    port: 443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_33"
    type: trojan
    server: "ger6.fytpn.com"
    port: 2097
    password: "gHncxmRjWEJ7apX5XuXsHw4kGexMH_gU"
    sni: "ger6.fytpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_34"
    type: trojan
    server: "nnnmjju.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_35"
    type: trojan
    server: "135.181.41.169"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "nnnmjju.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_36"
    type: trojan
    server: "194.87.6.192"
    port: 2097
    password: "gHncxmRjWEJ7apX5XuXsHw4kGexMH_gU"
    sni: "ger6.fytpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_37"
    type: trojan
    server: "vvbgh.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "vvbgh.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_38"
    type: trojan
    server: "bbbnnmj.131.pp.ua"
    port: 443
    password: "98b419ef-83a2-4d1b-a23d-566b7f24477b"
    sni: "bbbnnmj.131.pp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇮_39"
    type: ss
    server: "185.103.110.68"
    port: 18283
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_40"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_41"
    type: ss
    server: "185.103.110.66"
    port: 18280
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_42"
    type: ss
    server: "185.103.110.66"
    port: 18280
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_43"
    type: ss
    server: "185.103.110.68"
    port: 18283
    cipher: "aes-128-gcm"
    password: "f9300a9bf39ae0347c3a3bfbc4dd7754"
    udp: true
  - name: "🇫🇮_44"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_45"
    type: ss
    server: "95.85.250.78"
    port: 443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
  - name: "🇫🇮_46"
    type: ss
    server: "45.149.114.171"
    port: 777
    cipher: "chacha20-ietf-poly1305"
    password: "Jeoq8ujfkqZKKvACQhoqBQ1PA3uq4242"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"
      - "🇫🇮_29"
      - "🇫🇮_30"
      - "🇫🇮_31"
      - "🇫🇮_32"
      - "🇫🇮_33"
      - "🇫🇮_34"
      - "🇫🇮_35"
      - "🇫🇮_36"
      - "🇫🇮_37"
      - "🇫🇮_38"
      - "🇫🇮_39"
      - "🇫🇮_40"
      - "🇫🇮_41"
      - "🇫🇮_42"
      - "🇫🇮_43"
      - "🇫🇮_44"
      - "🇫🇮_45"
      - "🇫🇮_46"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇮_1"
      - "🇫🇮_2"
      - "🇫🇮_3"
      - "🇫🇮_4"
      - "🇫🇮_5"
      - "🇫🇮_6"
      - "🇫🇮_7"
      - "🇫🇮_8"
      - "🇫🇮_9"
      - "🇫🇮_10"
      - "🇫🇮_11"
      - "🇫🇮_12"
      - "🇫🇮_13"
      - "🇫🇮_14"
      - "🇫🇮_15"
      - "🇫🇮_16"
      - "🇫🇮_17"
      - "🇫🇮_18"
      - "🇫🇮_19"
      - "🇫🇮_20"
      - "🇫🇮_21"
      - "🇫🇮_22"
      - "🇫🇮_23"
      - "🇫🇮_24"
      - "🇫🇮_25"
      - "🇫🇮_26"
      - "🇫🇮_27"
      - "🇫🇮_28"
      - "🇫🇮_29"
      - "🇫🇮_30"
      - "🇫🇮_31"
      - "🇫🇮_32"
      - "🇫🇮_33"
      - "🇫🇮_34"
      - "🇫🇮_35"
      - "🇫🇮_36"
      - "🇫🇮_37"
      - "🇫🇮_38"
      - "🇫🇮_39"
      - "🇫🇮_40"
      - "🇫🇮_41"
      - "🇫🇮_42"
      - "🇫🇮_43"
      - "🇫🇮_44"
      - "🇫🇮_45"
      - "🇫🇮_46"

rules:
  - MATCH,PROXY
