name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇫🇷_1"
    type: vless
    server: "152.228.139.33"
    port: 51671
    uuid: "75cc7568-abb0-46a8-88be-8137d3c647d4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-5PowNUY37Pi01YKO9fjRTrum1m_9n6XauaPDpmOJzU"
      short-id: "2fed44d8c59f7e71"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc_common3"
  - name: "🇫🇷_2"
    type: vless
    server: "62.210.91.2"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_3"
    type: vless
    server: "51.77.217.70"
    port: 2053
    uuid: "bf16ee0c-8b3c-41e4-ab3a-8b48033c404e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g63cT3uI0Y5iUtj3m__RYz7nmR1eIK4AYikdnZCl63w"
      short-id: "bfe58beb41f1d09f"
  - name: "🇫🇷_4"
    type: vless
    server: "157.228.155.185"
    port: 443
    uuid: "df53b6c2-8005-475c-9eb9-74e1be785dc8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "4q8nqNb-0c-akP3XqVmen67BLXJVlx48a_GDRw16nVg"
      short-id: "5ea112e8"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_5"
    type: vless
    server: "rgiw5k0gg5-1492025789-direct.kheibarr.com"
    port: 443
    uuid: "rgiw5k0gg5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rgiw5k0gg5-1492025789-direct.kheibarr.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_6"
    type: vless
    server: "145.223.68.58"
    port: 443
    uuid: "edb50d20-2d3e-4c1e-8a75-a17168a89aa5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "qc2DcqT9zPPZr6ePZ7ukxACWrYhRNIBjDIjCK7veyQg"
      short-id: "a44ff7d2e80213c2"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_7"
    type: vless
    server: "edge.bookmai.com"
    port: 443
    uuid: "b9bfa54d-bc44-4592-a6d6-89a9665d286f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mother-earth.fyi"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_8"
    type: vless
    server: "51.255.166.202"
    port: 443
    uuid: "593bf46b-8316-5050-9357-d8a41e4db78b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "e3k67dwms3-51255166202-direct.tavafog.com"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_9"
    type: vless
    server: "157.228.155.238"
    port: 443
    uuid: "4d852af3-a121-41aa-9aed-4ca40a6f7b4d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5BDht3tAZdKEKpJymGlRK9JugOnieA-kMSWz_0FoE0I"
      short-id: "6f76ad09"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_10"
    type: vless
    server: "62.210.91.10"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_11"
    type: vless
    server: "51.255.165.170"
    port: 443
    uuid: "tyxyrytyro"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tyxyrytyro-51255165170-direct.araghchy.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_12"
    type: vless
    server: "e3k67dwms3-51255166202-direct.tavafog.com"
    port: 443
    uuid: "e3k67dwms3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "e3k67dwms3-51255166202-direct.tavafog.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_13"
    type: vless
    server: "tyxyrytyro-51255165170-direct.araghchy.com"
    port: 443
    uuid: "tyxyrytyro"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tyxyrytyro-51255165170-direct.araghchy.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_14"
    type: vless
    server: "51.255.166.202"
    port: 443
    uuid: "e3k67dwms3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "e3k67dwms3-51255166202-direct.tavafog.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_15"
    type: vless
    server: "137.74.16.237"
    port: 443
    uuid: "aaec4e42-a095-44b6-a239-f16d234a0798"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7LSzvilTVKGMtBDuKGeMrLtlhY7tQf5YcG566dEgO0I"
      short-id: "b390e0a721d242b0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_16"
    type: vless
    server: "194.76.154.31"
    port: 40443
    uuid: "9f0baff8-bdee-4de9-9515-bcc4932b41fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    reality-opts:
      public-key: "MN6QjUHDUXyteMdR-cDna89fq4X3qgQhLnNqTtRUbBQ"
      short-id: "a8ae"
  - name: "🇫🇷_17"
    type: vless
    server: "e3k67dwms3-51255166202-direct.tavafog.com"
    port: 443
    uuid: "593bf46b-8316-5050-9357-d8a41e4db78b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "e3k67dwms3-51255166202-direct.tavafog.com"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_18"
    type: vless
    server: "152.228.139.33"
    port: 35108
    uuid: "81dc0b61-f9fe-4ad6-8b4e-b8c067b73712"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    reality-opts:
      public-key: "X_lOw5Zz4SJBa1cRHV4dAq5msYE-ClY5-WNcBmBWRxg"
      short-id: "52add08b86a5ccea"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-common3"
  - name: "🇫🇷_19"
    type: vless
    server: "135.125.248.200"
    port: 27250
    uuid: "36b98b4a-fc76-4738-bd7d-274ca800c8fd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "image.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bqV9CFadimhl6zgliRrOdx-XoJ0vioLqmwxU4tWjTgc"
      short-id: "8d1e96"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc_common1"
  - name: "🇫🇷_20"
    type: vless
    server: "node-uk.connectsuite.org"
    port: 8443
    uuid: "c08f0056-7a6d-4931-813b-aaa3cdd00aed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node-uk.connectsuite.org"
    client-fingerprint: "chrome"
  - name: "🇫🇷_21"
    type: vless
    server: "195.154.118.134"
    port: 443
    uuid: "3c48b5f5-7766-4896-874e-b3ba1860e83a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "w-mebel.pro"
    client-fingerprint: "random"
    reality-opts:
      public-key: "YhT24GkuI1r7Fwo8pxIYH3CmTtbRlYs5X7fWtYp3vTY"
      short-id: "05f4f85fdc6c1379"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_22"
    type: vless
    server: "157.228.155.238"
    port: 443
    uuid: "df53b6c2-8005-475c-9eb9-74e1be785dc8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5BDht3tAZdKEKpJymGlRK9JugOnieA-kMSWz_0FoE0I"
      short-id: "6f76ad09"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_23"
    type: trojan
    server: "162.19.10.218"
    port: 443
    password: "af4b064a9c39472fb34ad8b113acdc6b"
    sni: "162.19.10.218"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_24"
    type: trojan
    server: "92.205.184.138"
    port: 443
    password: "AnadoluSpeed"
    sni: "telegram.org"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_25"
    type: trojan
    server: "54.36.191.211"
    port: 443
    password: "9855d850-5872-11ed-b133-225401db9d57"
    sni: "Blog.Irancell.IR"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_26"
    type: trojan
    server: "tr1.euroline.cloud"
    port: 443
    password: "AnadoluSpeed"
    sni: "telegram.org"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_27"
    type: trojan
    server: "54.36.191.211"
    port: 443
    password: "364d3aa0-58fc-11ed-b738-225401db9d57"
    sni: "ebank.bmi.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_28"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_29"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_30"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇫🇷_31"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇫🇷_32"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_33"
    type: ss
    server: "57.129.113.16"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "NcAXc0UZI6yQJE1p8QmOv8"
    udp: true
  - name: "🇫🇷_34"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇫🇷_35"
    type: ss
    server: "57.129.113.16"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "NcAXc0UZI6yQJE1p8QmOv8"
    udp: true
  - name: "🇫🇷_36"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇷_1"
      - "🇫🇷_2"
      - "🇫🇷_3"
      - "🇫🇷_4"
      - "🇫🇷_5"
      - "🇫🇷_6"
      - "🇫🇷_7"
      - "🇫🇷_8"
      - "🇫🇷_9"
      - "🇫🇷_10"
      - "🇫🇷_11"
      - "🇫🇷_12"
      - "🇫🇷_13"
      - "🇫🇷_14"
      - "🇫🇷_15"
      - "🇫🇷_16"
      - "🇫🇷_17"
      - "🇫🇷_18"
      - "🇫🇷_19"
      - "🇫🇷_20"
      - "🇫🇷_21"
      - "🇫🇷_22"
      - "🇫🇷_23"
      - "🇫🇷_24"
      - "🇫🇷_25"
      - "🇫🇷_26"
      - "🇫🇷_27"
      - "🇫🇷_28"
      - "🇫🇷_29"
      - "🇫🇷_30"
      - "🇫🇷_31"
      - "🇫🇷_32"
      - "🇫🇷_33"
      - "🇫🇷_34"
      - "🇫🇷_35"
      - "🇫🇷_36"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇫🇷_1"
      - "🇫🇷_2"
      - "🇫🇷_3"
      - "🇫🇷_4"
      - "🇫🇷_5"
      - "🇫🇷_6"
      - "🇫🇷_7"
      - "🇫🇷_8"
      - "🇫🇷_9"
      - "🇫🇷_10"
      - "🇫🇷_11"
      - "🇫🇷_12"
      - "🇫🇷_13"
      - "🇫🇷_14"
      - "🇫🇷_15"
      - "🇫🇷_16"
      - "🇫🇷_17"
      - "🇫🇷_18"
      - "🇫🇷_19"
      - "🇫🇷_20"
      - "🇫🇷_21"
      - "🇫🇷_22"
      - "🇫🇷_23"
      - "🇫🇷_24"
      - "🇫🇷_25"
      - "🇫🇷_26"
      - "🇫🇷_27"
      - "🇫🇷_28"
      - "🇫🇷_29"
      - "🇫🇷_30"
      - "🇫🇷_31"
      - "🇫🇷_32"
      - "🇫🇷_33"
      - "🇫🇷_34"
      - "🇫🇷_35"
      - "🇫🇷_36"

rules:
  - MATCH,PROXY
