name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇪_1"
    type: vless
    server: "198.55.102.59"
    port: 4443
    uuid: "7f86f371-5a85-48be-babc-7af1ae7ffb75"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "9gYnZLxZAPxIKzu9e-cOLBpbCn9p9og9gBodOCh5HB8"
      short-id: "ce6767c3f1"
    flow: "xtls-rprx-vision"
  - name: "🇮🇪_2"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_3"
    type: trojan
    server: "cosmic-shepherd.rooster465.autos"
    port: 443
    password: "PD07395842"
    sni: "cosmic-shepherd.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_4"
    type: trojan
    server: "proven-stud.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "proven-stud.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_5"
    type: trojan
    server: "52.208.138.36"
    port: 443
    password: "IQ68037294"
    sni: "vast-turkey.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_6"
    type: trojan
    server: "verified-ringtail.rooster465.autos"
    port: 443
    password: "NQ26071394"
    sni: "verified-ringtail.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_7"
    type: trojan
    server: "immune-mullet.rooster465.autos"
    port: 443
    password: "XG59623478"
    sni: "immune-mullet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_8"
    type: trojan
    server: "34.242.77.118"
    port: 443
    password: "UX82473651"
    sni: "sacred-anemone.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_9"
    type: trojan
    server: "sacred-anemone.rooster465.autos"
    port: 443
    password: "UX82473651"
    sni: "sacred-anemone.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_10"
    type: trojan
    server: "34.255.124.67"
    port: 443
    password: "EQ30679154"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_11"
    type: trojan
    server: "master-possum.rooster465.autos"
    port: 443
    password: "UX82473651"
    sni: "master-possum.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_12"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_13"
    type: trojan
    server: "immune-mullet.rooster465.autos"
    port: 443
    password: "CF68213490"
    sni: "immune-mullet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_14"
    type: trojan
    server: "proven-stud.rooster465.autos"
    port: 443
    password: "JA96378052"
    sni: "proven-stud.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_15"
    type: trojan
    server: "3.253.106.233"
    port: 443
    password: "UX82473651"
    sni: "loved-shark.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_16"
    type: trojan
    server: "52.208.138.36"
    port: 443
    password: "ON38567014"
    sni: "vast-turkey.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_17"
    type: trojan
    server: "adapting-basilisk.rooster465.autos"
    port: 443
    password: "UX82473651"
    sni: "adapting-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_18"
    type: trojan
    server: "well-goshawk.rooster465.autos"
    port: 443
    password: "ON38567014"
    sni: "well-goshawk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇪_19"
    type: trojan
    server: "loved-shark.rooster465.autos"
    port: 443
    password: "UX82473651"
    sni: "loved-shark.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇪_1"
      - "🇮🇪_2"
      - "🇮🇪_3"
      - "🇮🇪_4"
      - "🇮🇪_5"
      - "🇮🇪_6"
      - "🇮🇪_7"
      - "🇮🇪_8"
      - "🇮🇪_9"
      - "🇮🇪_10"
      - "🇮🇪_11"
      - "🇮🇪_12"
      - "🇮🇪_13"
      - "🇮🇪_14"
      - "🇮🇪_15"
      - "🇮🇪_16"
      - "🇮🇪_17"
      - "🇮🇪_18"
      - "🇮🇪_19"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇪_1"
      - "🇮🇪_2"
      - "🇮🇪_3"
      - "🇮🇪_4"
      - "🇮🇪_5"
      - "🇮🇪_6"
      - "🇮🇪_7"
      - "🇮🇪_8"
      - "🇮🇪_9"
      - "🇮🇪_10"
      - "🇮🇪_11"
      - "🇮🇪_12"
      - "🇮🇪_13"
      - "🇮🇪_14"
      - "🇮🇪_15"
      - "🇮🇪_16"
      - "🇮🇪_17"
      - "🇮🇪_18"
      - "🇮🇪_19"

rules:
  - MATCH,PROXY
