name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇮🇳_1"
    type: vless
    server: "139.84.220.85"
    port: 443
    uuid: "d90087c3-54f5-4283-a13f-615260c8b0c7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "googleapis.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "hTweFDvbSucrGERtiiwDfoqD3vo_Z9cuaqboff3FTXQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_2"
    type: vless
    server: "5.253.42.164"
    port: 40443
    uuid: "e99ba96d-dec8-42eb-be53-19e71eef7cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_3"
    type: vless
    server: "148.113.5.44"
    port: 443
    uuid: "72ea5a91-ffcc-43d2-9297-5993c3abf186"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QLjTpkXRB453R9fXhJzKkc_q_gSm2MZrIOuxW4uW-mI"
      short-id: "221873918e0bb74d"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_4"
    type: vless
    server: "dorado.yokkastars.com"
    port: 40443
    uuid: "af5eac96-e478-488a-bc8c-45269d7e8847"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_5"
    type: vless
    server: "5.253.28.224"
    port: 40443
    uuid: "af5eac96-e478-488a-bc8c-45269d7e8847"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_6"
    type: vless
    server: "103.194.228.102"
    port: 4443
    uuid: "f247f7e4-04bb-48a5-828d-b8e75ec4c3af"
    udp: true
  - name: "🇮🇳_7"
    type: vless
    server: "194.61.31.126"
    port: 2053
    uuid: "1d4e18bd-1f26-4915-b35a-7ace4826e76a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PuAGLfJy6cu1TNoHuKIKSxPetCbZI41fc8hQDjWPIAU"
      short-id: "9980e0609b0d3891"
  - name: "🇮🇳_8"
    type: trojan
    server: "65.20.82.177"
    port: 443
    password: "Tg3RnK7Xp8B1"
    sni: "ash.d50f6225-23b4-3a7b-9f15-a0fb2fc16803.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_9"
    type: trojan
    server: "hyfuuf6.wsone.icu"
    port: 443
    password: "M7v%w11Se*"
    sni: "hyfuuf6.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_10"
    type: trojan
    server: "185.67.125.147"
    port: 443
    password: "3747000103274291200"
    sni: "polished-collie.adder289.quest"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_11"
    type: trojan
    server: "34.131.228.210"
    port: 443
    password: "M7v%w11Se*"
    sni: "hyfuuf6.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_12"
    type: trojan
    server: "tttyder.wsone.icu"
    port: 443
    password: "M7v%w11Se*"
    sni: "tttyder.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_13"
    type: trojan
    server: "143.110.246.228"
    port: 443
    password: "3bcd9e33-8377-4b32-af33-217158577ff3"
    sni: "kdlsupport.zendesk.com"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_14"
    type: trojan
    server: "185.67.125.147"
    port: 443
    password: "3763495894587285504"
    sni: "optimal-owl.goat627.mom"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_15"
    type: trojan
    server: "35.244.28.130"
    port: 443
    password: "M7v%w11Se*"
    sni: "tttyder.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_16"
    type: trojan
    server: "185.67.125.119"
    port: 443
    password: "3747000103274291200"
    sni: "oriented-pug.adder289.quest"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_17"
    type: trojan
    server: "64.227.131.19"
    port: 443
    password: "21c6c7cb-332b-4a0c-9ad7-dff9c3111442"
    sni: "us02web.zoom.us"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_18"
    type: ss
    server: "45.149.114.171"
    port: 777
    cipher: "chacha20-ietf-poly1305"
    password: "Jeoq8ujfkqZKKvACQhoqBQ1PA3uq4242"
    udp: true
  - name: "🇮🇳_19"
    type: ss
    server: "103.181.177.88"
    port: 443
    cipher: "none"
    password: "14b02e2a-8930-4afb-8412-ea4a4954ca5b"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "14b02e2a-8930-4afb-8412-ea4a4954ca5b/?ed\\=2560"
      host: "ylnhh.us.ci"
  - name: "🇮🇳_20"
    type: ss
    server: "172.105.39.124"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇮🇳_21"
    type: ss
    server: "172.105.39.124"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇮🇳_22"
    type: ss
    server: "103.181.177.88"
    port: 443
    cipher: "none"
    password: "14b02e2a-8930-4afb-8412-ea4a4954ca5b"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "14b02e2a-8930-4afb-8412-ea4a4954ca5b/?ed\\=2560"
      host: "ylnhh.us.ci"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇳_1"
      - "🇮🇳_2"
      - "🇮🇳_3"
      - "🇮🇳_4"
      - "🇮🇳_5"
      - "🇮🇳_6"
      - "🇮🇳_7"
      - "🇮🇳_8"
      - "🇮🇳_9"
      - "🇮🇳_10"
      - "🇮🇳_11"
      - "🇮🇳_12"
      - "🇮🇳_13"
      - "🇮🇳_14"
      - "🇮🇳_15"
      - "🇮🇳_16"
      - "🇮🇳_17"
      - "🇮🇳_18"
      - "🇮🇳_19"
      - "🇮🇳_20"
      - "🇮🇳_21"
      - "🇮🇳_22"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇮🇳_1"
      - "🇮🇳_2"
      - "🇮🇳_3"
      - "🇮🇳_4"
      - "🇮🇳_5"
      - "🇮🇳_6"
      - "🇮🇳_7"
      - "🇮🇳_8"
      - "🇮🇳_9"
      - "🇮🇳_10"
      - "🇮🇳_11"
      - "🇮🇳_12"
      - "🇮🇳_13"
      - "🇮🇳_14"
      - "🇮🇳_15"
      - "🇮🇳_16"
      - "🇮🇳_17"
      - "🇮🇳_18"
      - "🇮🇳_19"
      - "🇮🇳_20"
      - "🇮🇳_21"
      - "🇮🇳_22"

rules:
  - MATCH,PROXY
