name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇱🇹_1"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "b60cab55-e7a1-413d-a297-ddd7bad3fb62"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "bbcab8fa80a3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_2"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "ff40696b-06d6-443b-9481-8d01eddd13e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "d659da01fb94"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_3"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "ed042cf7-efe0-49bd-848b-8d7e655111ff"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "1036b2383b72"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_4"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "1896c6c9-a941-4688-a865-29027bf7f8e6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "6c825bc79850"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_5"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "2f6e2b17-4d5e-4a12-8979-f53fdd347580"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "5c8a8e6c615b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_6"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "594d466e-8ac3-4fda-b1d1-eeb817853518"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "5a018643df03"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_7"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "455cfdc6-9abf-4e40-863f-5ff6cc63457c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "18e4d2d21241"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_8"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "455cfdc6-9abf-4e40-863f-5ff6cc63457c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "18e4d2d21241"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_9"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "13aef2e0-b3fb-4322-a0e9-c10b908ce6b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.techradar.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "87f895f23064"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_10"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "106d20f6-d70a-40e2-b69b-8e82baf8d117"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "60500a63ad12"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_11"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "ee39fb11-56a3-4ee7-9e7c-35a4235bd30e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "b27ba098687b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_12"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "1896c6c9-a941-4688-a865-29027bf7f8e6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "6c825bc79850"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_13"
    type: vless
    server: "87.239.249.137"
    port: 443
    uuid: "67eb6b17-7797-4ded-bf52-423c4c5f6cbd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "G7bpUPFSW28-oE6ff8qZac1_apU6PiJ-GHmi7tAPDSY"
      short-id: "91af08b1ce1f"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_14"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "fad0b9a6-187d-4fcc-96fc-498bc5b3135a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "8325360e8bd2"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_15"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "aded66f1-de12-4c3c-af9e-a21d6e7d9c96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "2a80364e93d9"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_16"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "aded66f1-de12-4c3c-af9e-a21d6e7d9c96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "2a80364e93d9"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_17"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "2ba7f500-017b-4891-87a0-e4e62a4ad52d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "9409f73c2fd7"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_18"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "6dfc9149-1ff9-41c3-8563-0ef284381731"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "1374bddeb25d"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_19"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "d84c13b2-c2b9-4a7c-838f-05ac09ee422e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "2a2ce9e42980"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_20"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "4d017db2-7655-4276-9557-e2ec25b04ee7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "ee1716767f9b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_21"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "68cf8d29-5aa0-44b3-88a9-f1a576b6e84c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "73a9e631a09b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_22"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "6dfc9149-1ff9-41c3-8563-0ef284381731"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "1374bddeb25d"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_23"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "de38389f-5651-4f2f-8276-5aabf3b861c9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.hollywoodreporter.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "225e930cfd4d"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_24"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "317bc783-340f-453c-afb5-b6bf637c0b23"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "fc994ae7eb10"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_25"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "ee39fb11-56a3-4ee7-9e7c-35a4235bd30e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "b27ba098687b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_26"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "ff40696b-06d6-443b-9481-8d01eddd13e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "d659da01fb94"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_27"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "106d20f6-d70a-40e2-b69b-8e82baf8d117"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "60500a63ad12"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_28"
    type: vless
    server: "lists.soloramtin.cyou"
    port: 443
    uuid: "67eb6b17-7797-4ded-bf52-423c4c5f6cbd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "G7bpUPFSW28-oE6ff8qZac1_apU6PiJ-GHmi7tAPDSY"
      short-id: "91af08b1ce1f"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_29"
    type: vless
    server: "62.77.158.1"
    port: 443
    uuid: "2eceaf2b-a775-5a9c-9990-dad2b3660fb6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "online.1c.ru"
    reality-opts:
      public-key: "sVhkyiMXvpofflCdSszxQmsqOXV1kg1Ldxq1a9mOPjs"
      short-id: "6a"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_30"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "13aef2e0-b3fb-4322-a0e9-c10b908ce6b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.techradar.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "87f895f23064"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_31"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "fad0b9a6-187d-4fcc-96fc-498bc5b3135a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "8325360e8bd2"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_32"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "317bc783-340f-453c-afb5-b6bf637c0b23"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "fc994ae7eb10"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_33"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "4d017db2-7655-4276-9557-e2ec25b04ee7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "ee1716767f9b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_34"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "2f6e2b17-4d5e-4a12-8979-f53fdd347580"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "5c8a8e6c615b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_35"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "594d466e-8ac3-4fda-b1d1-eeb817853518"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "5a018643df03"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_36"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "d84c13b2-c2b9-4a7c-838f-05ac09ee422e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "2a2ce9e42980"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_37"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "2ba7f500-017b-4891-87a0-e4e62a4ad52d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "9409f73c2fd7"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_38"
    type: vless
    server: "server.slavkiti.monster"
    port: 443
    uuid: "ed042cf7-efe0-49bd-848b-8d7e655111ff"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "1036b2383b72"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_39"
    type: vless
    server: "107.181.151.39"
    port: 443
    uuid: "b60cab55-e7a1-413d-a297-ddd7bad3fb62"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "J-dv-HrWfQ_IOoyutv0Kg-rO8QwoRwc02dS1dS_tblk"
      short-id: "bbcab8fa80a3"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"
      - "🇱🇹_9"
      - "🇱🇹_10"
      - "🇱🇹_11"
      - "🇱🇹_12"
      - "🇱🇹_13"
      - "🇱🇹_14"
      - "🇱🇹_15"
      - "🇱🇹_16"
      - "🇱🇹_17"
      - "🇱🇹_18"
      - "🇱🇹_19"
      - "🇱🇹_20"
      - "🇱🇹_21"
      - "🇱🇹_22"
      - "🇱🇹_23"
      - "🇱🇹_24"
      - "🇱🇹_25"
      - "🇱🇹_26"
      - "🇱🇹_27"
      - "🇱🇹_28"
      - "🇱🇹_29"
      - "🇱🇹_30"
      - "🇱🇹_31"
      - "🇱🇹_32"
      - "🇱🇹_33"
      - "🇱🇹_34"
      - "🇱🇹_35"
      - "🇱🇹_36"
      - "🇱🇹_37"
      - "🇱🇹_38"
      - "🇱🇹_39"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"
      - "🇱🇹_9"
      - "🇱🇹_10"
      - "🇱🇹_11"
      - "🇱🇹_12"
      - "🇱🇹_13"
      - "🇱🇹_14"
      - "🇱🇹_15"
      - "🇱🇹_16"
      - "🇱🇹_17"
      - "🇱🇹_18"
      - "🇱🇹_19"
      - "🇱🇹_20"
      - "🇱🇹_21"
      - "🇱🇹_22"
      - "🇱🇹_23"
      - "🇱🇹_24"
      - "🇱🇹_25"
      - "🇱🇹_26"
      - "🇱🇹_27"
      - "🇱🇹_28"
      - "🇱🇹_29"
      - "🇱🇹_30"
      - "🇱🇹_31"
      - "🇱🇹_32"
      - "🇱🇹_33"
      - "🇱🇹_34"
      - "🇱🇹_35"
      - "🇱🇹_36"
      - "🇱🇹_37"
      - "🇱🇹_38"
      - "🇱🇹_39"

rules:
  - MATCH,PROXY
