name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇱🇻_1"
    type: vless
    server: "lit.fytpn.com"
    port: 56789
    uuid: "a889fba5-5472-4022-a6b4-9710157fda2f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lit.fytpn.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PDHRi_RRFsPhxLoH2C1l9A9HdL2y7g1uOzXmY0XnmzQ"
      short-id: "a2aa"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_2"
    type: vless
    server: "138.124.63.93"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lv-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_3"
    type: vless
    server: "138.124.63.94"
    port: 443
    uuid: "2b781b4a-5942-48e0-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lv-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_4"
    type: vless
    server: "31.57.106.241"
    port: 443
    uuid: "a4801105-c0c7-4cab-87c6-f257ff2afc09"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.lmt.lv"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "4SJB--DChFNhmOUz0-BZK2dS3GhZ1yZwMVIhmpobB0o"
      short-id: "44f7c5615039ae1b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_5"
    type: vless
    server: "138.124.63.94"
    port: 443
    uuid: "2b781b4a-5942-0018-a7f3-5a07b7b488c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lv-root.sworkingvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AhLy7ha7FF2EQfu-3SxOFKUwExyHActYPHtyv82KNCI"
      short-id: "15bcc0a77c3cacdf"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_6"
    type: vless
    server: "138.124.180.137"
    port: 443
    uuid: "5234b2b7-5e07-422c-8159-d62a676c00c6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "GBdkyDLfr0LIZo_94Xv8ycAKOmkjArYzwJAEMhuXX2c"
      short-id: "33acba1b"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_7"
    type: vless
    server: "216.173.71.43"
    port: 443
    uuid: "ee18d188-14cc-417e-beb1-70e4add6d023"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lv.nztvpn.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "miDhSALrcCvSfc38VjCDYlzNh5M61NMR5IkUli7IN08"
      short-id: "0da7e14db353e7d0"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_8"
    type: vless
    server: "195.123.213.28"
    port: 443
    uuid: "02fcc1a4-ee90-4970-8bbb-4ffaa8109d24"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "NMgy1XgCSXExOg6Tg8xG9lCWttMF6sjdpB41lZy6FWo"
      short-id: "5c256336e3b673fa"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_9"
    type: trojan
    server: "lit.fytpn.com"
    port: 2097
    password: "gHncxmRjWEJ7apX5XuXsHw4kGexMH_gU"
    sni: "lit.fytpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇱🇻_10"
    type: ss
    server: "46.32.186.85"
    port: 443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "3e96ef7d-8637-42c2-ac73-75182196e755/?ed\\=2560"
      host: "mfvpn.fuchen.indevs.in"
      tls: true
  - name: "🇱🇻_11"
    type: ss
    server: "46.32.186.85"
    port: 443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "3e96ef7d-8637-42c2-ac73-75182196e755/?ed\\=2560"
      host: "mfvpn.fuchen.indevs.in"
      tls: true
  - name: "🇱🇻_12"
    type: ss
    server: "193.68.89.220"
    port: 8443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "3e96ef7d-8637-42c2-ac73-75182196e755/?ed\\=2560"
      host: "mfvpn.fuchen.indevs.in"
      tls: true
  - name: "🇱🇻_13"
    type: ss
    server: "193.68.89.220"
    port: 8443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "3e96ef7d-8637-42c2-ac73-75182196e755/?ed\\=2560"
      host: "mfvpn.fuchen.indevs.in"
      tls: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇻_1"
      - "🇱🇻_2"
      - "🇱🇻_3"
      - "🇱🇻_4"
      - "🇱🇻_5"
      - "🇱🇻_6"
      - "🇱🇻_7"
      - "🇱🇻_8"
      - "🇱🇻_9"
      - "🇱🇻_10"
      - "🇱🇻_11"
      - "🇱🇻_12"
      - "🇱🇻_13"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇱🇻_1"
      - "🇱🇻_2"
      - "🇱🇻_3"
      - "🇱🇻_4"
      - "🇱🇻_5"
      - "🇱🇻_6"
      - "🇱🇻_7"
      - "🇱🇻_8"
      - "🇱🇻_9"
      - "🇱🇻_10"
      - "🇱🇻_11"
      - "🇱🇻_12"
      - "🇱🇻_13"

rules:
  - MATCH,PROXY
