name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇷🇴_1"
    type: vless
    server: "46.28.67.55"
    port: 443
    uuid: "d1a6a033-fdbd-46a6-a177-3370ba042b9f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "i2dJ1_XGDpp50qpEclh6SWSWkxt4B0t2hi2qOVQbeSU"
      short-id: "d06d78e974491b6e"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_2"
    type: vless
    server: "146.70.124.85"
    port: 443
    uuid: "40abbe13-f02e-4da2-9b19-966c2c3eb4ee"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.datadoghq.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "byzvlw97wjAAAfHs5AZRV0P0H6_JKBEZ4yfLS0HNewE"
      short-id: "fe24f8a0a560056e"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_3"
    type: ss
    server: "bogging-eyeteeth-fly.freesocks.work"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "QFWzCw2uX9B9i6qAYeFBIE"
    udp: true
  - name: "🇷🇴_4"
    type: ss
    server: "154.46.31.106"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "QFWzCw2uX9B9i6qAYeFBIE"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇴_1"
      - "🇷🇴_2"
      - "🇷🇴_3"
      - "🇷🇴_4"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇷🇴_1"
      - "🇷🇴_2"
      - "🇷🇴_3"
      - "🇷🇴_4"

rules:
  - MATCH,PROXY
