name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "gw1.edgemedia.lol"
    port: 13443
    uuid: "9ebf4fda-7395-4800-b42f-b2dda649880a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1MLoHw7RVkGefh7XUyuGg4ndxwv4vDU9en-f9JxpXRQ"
      short-id: "d2061bb1"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_2"
    type: vless
    server: "du-rov.secureservice.top"
    port: 8443
    uuid: "c53ea5e9-ed8b-4990-805d-7f1d6451426c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "du-rov.secureservice.top"
    client-fingerprint: "random"
    reality-opts:
      public-key: "fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI"
      short-id: "3cbc3d737fb9c4af"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_3"
    type: vless
    server: "82.202.141.141"
    port: 9892
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_4"
    type: vless
    server: "5.42.99.64"
    port: 8443
    uuid: "c53ea5e9-ed8b-4990-805d-7f1d6451426c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "du-rov.secureservice.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fSVfR9NB-6J6smrZlavi0GWd8JfDh0aXuEkKbtuFzUI"
      short-id: "3cbc3d737fb9c4af"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_5"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_6"
    type: vless
    server: "87.228.92.108"
    port: 25178
    uuid: "95003356-20f9-4c84-a21f-2f9c1fc285eb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.icloud.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UTK3fM9wiII4uIcBYUYJwppN1HezxBPhxPfIxDHZqj4"
      short-id: "ce43937e79bc30f0"
  - name: "🇷🇺_7"
    type: vless
    server: "31.131.251.17"
    port: 443
    uuid: "9ea8b000-58ce-0050-b108-989dd4f248f1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "quatro.lmstream.org"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_8"
    type: vless
    server: "45.132.176.190"
    port: 9892
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_9"
    type: vless
    server: "185.147.27.183"
    port: 8443
    uuid: "379998c5-2a71-4202-9c74-522e0c3c5404"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "user-6a917f32.noooo.win"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_10"
    type: trojan
    server: "45.147.200.44"
    port: 443
    password: "265f092f-418b-30c9-a479-4800fd44dd19mielink"
    sni: "$$paydiu.com"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_11"
    type: trojan
    server: "188.225.37.70"
    port: 11443
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "msk1.cenza.cloud"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_12"
    type: trojan
    server: "tr-wien.unlimited-access.ru"
    port: 443
    password: "kxHw-Dk-e9dffgzYszMlEqLJ92AnY3Pi"
    sni: "tr-wien.unlimited-access.ru"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_13"
    type: trojan
    server: "217.16.17.127"
    port: 25565
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "vkc2.safesurf.cloud"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_14"
    type: trojan
    server: "185.241.195.185"
    port: 2224
    password: "WaGG8TGpKhcMU-F-e9vrjB7MnUHGPhtt"
    sni: "vkc9.secured-by-tenzo.sbs"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_15"
    type: trojan
    server: "ru2.x8lab.org"
    port: 9443
    password: "bVhfAPS7f_tagBb-G79z0zWB6L1yK84H"
    sni: "ru2.x8lab.org"
    skip-cert-verify: true
    udp: true
  - name: "🇷🇺_16"
    type: trojan
    server: "ru-1.krugvpn.com"
    port: 443
    password: "jj59d0f73f5d6"
    sni: "ru-1.krugvpn.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"

rules:
  - MATCH,PROXY
