name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "no.cnd.sweden.myfilecdn.com"
    port: 443
    uuid: "0d628b17-8ac4-49b9-a422-6b99077bfdf6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "CetY_ReGID1LBH275yWlxxOctI82PtgxR-fjYSRTKzM"
      short-id: "8a2b3c4d5e6f7012"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_2"
    type: vless
    server: "163.245.43.50"
    port: 443
    uuid: "203d434a-2a92-45df-8973-ca80434ecf73"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "se-twitch.global-cdn.org"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "content.v1.Feed"
  - name: "🇸🇪_3"
    type: vless
    server: "31.207.7.74"
    port: 443
    uuid: "2412bd96-925b-43f2-81d1-0ed4f0793699"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pkg.go.dev"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "RDL0RVmgFM3fdqXRSHBF2A53YF9TPFu2aeJQhMTaY3s"
      short-id: "457ae5b8bef4d1b3"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "31.76.3.34"
    port: 443
    uuid: "0d628b17-8ac4-49b9-a422-6b99077bfdf6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CetY_ReGID1LBH275yWlxxOctI82PtgxR-fjYSRTKzM"
      short-id: "8a2b3c4d5e6f7012"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_5"
    type: vless
    server: "swself2.yandex-api.com"
    port: 443
    uuid: "1b7ee703-fa08-4305-8469-ae3e30e61e44"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swself2.yandex-api.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "HXFe_cPryw01zqXchAFjZciDAS4UJg1-xScx6vjgjjY"
      short-id: "7f2e9c4b1a8d6e25"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "se3.h1cloud.net"
    port: 25119
    uuid: "f90b7d43-69e2-4b46-a672-8029bc6796a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "szPq4a3cvxfBOmGyg-UJCV3d1Jqjnj7YR3gaxyYtnk4"
      short-id: "10f517"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_7"
    type: vless
    server: "62.60.159.81"
    port: 2053
    uuid: "fc00adfb-232a-46ce-8b93-0c70e516aa8a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ygmJxS-Mc7g0buNSUTVGhazT-FoBjyYtLLfUYIQxFTw"
      short-id: "d0ea1847066af5a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpce5bb9e71"
  - name: "🇸🇪_8"
    type: vless
    server: "swidenlanzerotte.live"
    port: 443
    uuid: "56de13ac-086e-4789-8e1e-1bf2bd90216b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swidenlanzerotte.live"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "MQrvfivvEfLGzDee7h0j5uC-DwaD_38_NXOY9-NhqxM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_9"
    type: vless
    server: "177.3.209.245"
    port: 443
    uuid: "56de13ac-086e-4789-8e1e-1bf2bd90216b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swidenlanzerotte.live"
    reality-opts:
      public-key: "MQrvfivvEfLGzDee7h0j5uC-DwaD_38_NXOY9-NhqxM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_10"
    type: trojan
    server: "45.91.171.116"
    port: 443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "sto.freeguard.org"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"

rules:
  - MATCH,PROXY
