name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "78.135.73.47"
    port: 443
    uuid: "25e16692-d097-4e69-9e2d-8415609c1968"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.datadoghq.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sZAJkAu23wp1WKY-qeaeiwR38izP5OyfhumoE9xhbB8"
      short-id: "f46cd3ea3d1eb72d"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_2"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "0eed6293-8cf1-4e77-ac10-9c3d50d0b2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bYW_MmB_CUHrsyoCAUKviI2LZdHf63yY2yOPXbih104"
      short-id: "9e419c0759b54d6f"
  - name: "🇹🇷_3"
    type: vless
    server: "168.222.43.200"
    port: 2053
    uuid: "9ef61079-6f7d-4911-9608-943da85d8e6f"
    udp: true
  - name: "🇹🇷_4"
    type: vless
    server: "81.177.215.175"
    port: 443
    uuid: "1c5ed2e1-56da-41ab-9a78-159d9892ec17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "lHCkAu_DOVFtE-iL2JGrPt44QeTCFijXuRfuGaSni3Q"
      short-id: "9e4eced6e98ed4d4"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_5"
    type: vless
    server: "85.192.48.142"
    port: 443
    uuid: "adc11f30-e4cb-4985-bf5e-f9ded69c019f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nvidia.com"
    reality-opts:
      public-key: "fNfokzklCF4l_c8k8PciOCjm5ecNoF_sNLjEtaO-xzI"
      short-id: "db04ce8bdb8900f1"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_6"
    type: vless
    server: "212.74.39.188"
    port: 2053
    uuid: "9ef61079-6f7d-4911-9608-943da85d8e6f"
    udp: true
  - name: "🇹🇷_7"
    type: vless
    server: "test.keoplentuio.xyz"
    port: 2053
    uuid: "9ef61079-6f7d-4911-9608-943da85d8e6f"
    udp: true
  - name: "🇹🇷_8"
    type: trojan
    server: "194.87.39.133"
    port: 443
    password: "af4b064a9c39472fb34ad8b113acdc6b"
    sni: "194.87.39.133"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_9"
    type: trojan
    server: "194.146.26.40"
    port: 443
    password: "2ea5fc44-bd38-4fb0-a9b9-88c83fc56622"
    sni: "4-193-105-141.nhost.00cdn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇷_10"
    type: trojan
    server: "subtu.charsoulink3.ir"
    port: 2087
    password: "v2whz6ahmyy2f84j"
    sni: "pus.mmdaqaorg2.ir"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"
      - "🇹🇷_10"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"
      - "🇹🇷_10"

rules:
  - MATCH,PROXY
