name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇹🇼_1"
    type: vless
    server: "hinet1.2yly.com"
    port: 24215
    uuid: "19d5a678-8396-4e3b-93da-ece618d0e83a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "mdWKUPMVTtTbDqK10BPb89OcqBC2-Lx-4NOYtqc1GWE"
      short-id: ""
  - name: "🇹🇼_2"
    type: vless
    server: "61.230.162.88"
    port: 24215
    uuid: "19d5a678-8396-4e3b-93da-ece618d0e83a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mdWKUPMVTtTbDqK10BPb89OcqBC2-Lx-4NOYtqc1GWE"
      short-id: ""
  - name: "🇹🇼_3"
    type: trojan
    server: "211.20.156.191"
    port: 28155
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_4"
    type: trojan
    server: "a10.taipeicitygovernment.kyiv.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_5"
    type: trojan
    server: "211.20.156.191"
    port: 28157
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_6"
    type: trojan
    server: "211.20.156.191"
    port: 28162
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_7"
    type: trojan
    server: "211.20.156.191"
    port: 28122
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_8"
    type: trojan
    server: "211.20.156.191"
    port: 28158
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_9"
    type: trojan
    server: "211.20.156.191"
    port: 28156
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_10"
    type: trojan
    server: "a04.taipeicitygovernment.com.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_11"
    type: trojan
    server: "211.20.156.191"
    port: 28121
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_12"
    type: trojan
    server: "211.20.156.191"
    port: 28169
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_13"
    type: trojan
    server: "211.20.156.191"
    port: 28133
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_14"
    type: trojan
    server: "60.250.152.229"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_15"
    type: trojan
    server: "211.20.156.191"
    port: 28161
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_16"
    type: trojan
    server: "211.20.156.191"
    port: 28160
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_17"
    type: trojan
    server: "211.20.156.191"
    port: 28123
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_18"
    type: trojan
    server: "60.250.80.31"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_19"
    type: trojan
    server: "211.20.156.191"
    port: 28153
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_20"
    type: trojan
    server: "211.20.156.191"
    port: 28138
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_21"
    type: trojan
    server: "official.taipeicitygovernment.ivano-frankivsk.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.ivano-frankivsk.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_22"
    type: trojan
    server: "211.20.156.191"
    port: 28166
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_23"
    type: trojan
    server: "211.20.156.191"
    port: 28118
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_24"
    type: trojan
    server: "211.20.156.191"
    port: 28119
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_25"
    type: trojan
    server: "211.20.156.191"
    port: 28125
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_26"
    type: trojan
    server: "211.20.156.191"
    port: 28147
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_27"
    type: trojan
    server: "211.20.156.191"
    port: 28165
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_28"
    type: trojan
    server: "211.20.156.191"
    port: 28154
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_29"
    type: trojan
    server: "official.taipeicitygovernment.org.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.org.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_30"
    type: trojan
    server: "211.20.156.191"
    port: 28152
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_31"
    type: trojan
    server: "60.250.152.229"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.chernovtsy.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_32"
    type: trojan
    server: "a01.taipeicitygovernment.biz.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_33"
    type: trojan
    server: "211.20.156.191"
    port: 28159
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_34"
    type: trojan
    server: "a06.taipeicitygovernment.dp.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_35"
    type: trojan
    server: "211.20.156.191"
    port: 28120
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_36"
    type: trojan
    server: "official.taipeicitygovernment.com.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.com.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_37"
    type: trojan
    server: "211.20.156.191"
    port: 28145
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_38"
    type: trojan
    server: "211.20.156.191"
    port: 28150
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_39"
    type: trojan
    server: "211.20.156.191"
    port: 28167
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_40"
    type: trojan
    server: "a11.taipeicitygovernment.net.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_41"
    type: trojan
    server: "211.20.156.191"
    port: 28164
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_42"
    type: trojan
    server: "211.20.156.191"
    port: 28124
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_43"
    type: trojan
    server: "60.250.80.31"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.biz.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_44"
    type: trojan
    server: "211.20.156.191"
    port: 28163
    password: "i99Cef"
    sni: "ctldl.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_45"
    type: trojan
    server: "official.taipeicitygovernment.dp.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.dp.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_46"
    type: vmess
    server: "165.154.195.38"
    port: 35034
    uuid: "959a8caf-4cea-43d0-a548-3628e7ddfafc"
    alterId: 0
    cipher: "auto"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇼_1"
      - "🇹🇼_2"
      - "🇹🇼_3"
      - "🇹🇼_4"
      - "🇹🇼_5"
      - "🇹🇼_6"
      - "🇹🇼_7"
      - "🇹🇼_8"
      - "🇹🇼_9"
      - "🇹🇼_10"
      - "🇹🇼_11"
      - "🇹🇼_12"
      - "🇹🇼_13"
      - "🇹🇼_14"
      - "🇹🇼_15"
      - "🇹🇼_16"
      - "🇹🇼_17"
      - "🇹🇼_18"
      - "🇹🇼_19"
      - "🇹🇼_20"
      - "🇹🇼_21"
      - "🇹🇼_22"
      - "🇹🇼_23"
      - "🇹🇼_24"
      - "🇹🇼_25"
      - "🇹🇼_26"
      - "🇹🇼_27"
      - "🇹🇼_28"
      - "🇹🇼_29"
      - "🇹🇼_30"
      - "🇹🇼_31"
      - "🇹🇼_32"
      - "🇹🇼_33"
      - "🇹🇼_34"
      - "🇹🇼_35"
      - "🇹🇼_36"
      - "🇹🇼_37"
      - "🇹🇼_38"
      - "🇹🇼_39"
      - "🇹🇼_40"
      - "🇹🇼_41"
      - "🇹🇼_42"
      - "🇹🇼_43"
      - "🇹🇼_44"
      - "🇹🇼_45"
      - "🇹🇼_46"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇹🇼_1"
      - "🇹🇼_2"
      - "🇹🇼_3"
      - "🇹🇼_4"
      - "🇹🇼_5"
      - "🇹🇼_6"
      - "🇹🇼_7"
      - "🇹🇼_8"
      - "🇹🇼_9"
      - "🇹🇼_10"
      - "🇹🇼_11"
      - "🇹🇼_12"
      - "🇹🇼_13"
      - "🇹🇼_14"
      - "🇹🇼_15"
      - "🇹🇼_16"
      - "🇹🇼_17"
      - "🇹🇼_18"
      - "🇹🇼_19"
      - "🇹🇼_20"
      - "🇹🇼_21"
      - "🇹🇼_22"
      - "🇹🇼_23"
      - "🇹🇼_24"
      - "🇹🇼_25"
      - "🇹🇼_26"
      - "🇹🇼_27"
      - "🇹🇼_28"
      - "🇹🇼_29"
      - "🇹🇼_30"
      - "🇹🇼_31"
      - "🇹🇼_32"
      - "🇹🇼_33"
      - "🇹🇼_34"
      - "🇹🇼_35"
      - "🇹🇼_36"
      - "🇹🇼_37"
      - "🇹🇼_38"
      - "🇹🇼_39"
      - "🇹🇼_40"
      - "🇹🇼_41"
      - "🇹🇼_42"
      - "🇹🇼_43"
      - "🇹🇼_44"
      - "🇹🇼_45"
      - "🇹🇼_46"

rules:
  - MATCH,PROXY
