name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇻🇳_1"
    type: vless
    server: "150.95.109.109"
    port: 2086
    uuid: "b83faafc-cbb7-4655-99d4-2c4c39a49d1b"
    udp: true
  - name: "🇻🇳_2"
    type: vless
    server: "43.255.157.118"
    port: 44988
    uuid: "57beeeb0-03fc-4fc9-94da-7604488a7134"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f6Tj8-uvWsLv3V-lGLuPciArp5oKqUImBg-U7-WJ-0A"
      short-id: "bb82c8"
    flow: "xtls-rprx-vision"
  - name: "🇻🇳_3"
    type: vless
    server: "160.25.74.91"
    port: 443
    uuid: "30e52776-55ac-3cb4-8d36-e2910f07e2c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u695098ue79dbcd4s783.gogocs.xyz"
    flow: "xtls-rprx-vision"
  - name: "🇻🇳_4"
    type: vless
    server: "45.153.130.119"
    port: 44988
    uuid: "57beeeb0-03fc-4fc9-94da-7604488a7134"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "f6Tj8-uvWsLv3V-lGLuPciArp5oKqUImBg-U7-WJ-0A"
      short-id: "bb82c8"
    flow: "xtls-rprx-vision"
  - name: "🇻🇳_5"
    type: vless
    server: "103.30.76.65"
    port: 44988
    uuid: "57beeeb0-03fc-4fc9-94da-7604488a7134"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f6Tj8-uvWsLv3V-lGLuPciArp5oKqUImBg-U7-WJ-0A"
      short-id: "bb82c8"
    flow: "xtls-rprx-vision"
  - name: "🇻🇳_6"
    type: trojan
    server: "103.9.77.6"
    port: 443
    password: "c0f32867-001f-43f6-a0cc-9fd8730e5430"
    sni: "Free.Shecan.Ir"
    skip-cert-verify: true
    udp: true
  - name: "🇻🇳_7"
    type: trojan
    server: "103.9.77.6"
    port: 443
    password: "5a92d674-308c-4d95-b283-28383e63a59b"
    sni: "103.9.77.6"
    skip-cert-verify: true
    udp: true
  - name: "🇻🇳_8"
    type: trojan
    server: "36.50.134.29"
    port: 443
    password: "94d219c9-1afc-4d42-b090-8b3794764380"
    sni: "36.50.134.29"
    skip-cert-verify: true
    udp: true
  - name: "🇻🇳_9"
    type: trojan
    server: "38.54.15.140"
    port: 443
    password: "af4b064a9c39472fb34ad8b113acdc6b"
    sni: "38.54.15.140"
    skip-cert-verify: true
    udp: true
  - name: "🇻🇳_10"
    type: trojan
    server: "103.72.96.55"
    port: 443
    password: "c95357eb-2869-4511-8940-f0dc5e1ec9b1"
    sni: "hanoiidc2.5gsieutocdo.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇻🇳_1"
      - "🇻🇳_2"
      - "🇻🇳_3"
      - "🇻🇳_4"
      - "🇻🇳_5"
      - "🇻🇳_6"
      - "🇻🇳_7"
      - "🇻🇳_8"
      - "🇻🇳_9"
      - "🇻🇳_10"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇻🇳_1"
      - "🇻🇳_2"
      - "🇻🇳_3"
      - "🇻🇳_4"
      - "🇻🇳_5"
      - "🇻🇳_6"
      - "🇻🇳_7"
      - "🇻🇳_8"
      - "🇻🇳_9"
      - "🇻🇳_10"

rules:
  - MATCH,PROXY
