name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

fragment:
  enable: true
  size: "5-40"
  sleep: "1-2"

ttl: 5

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220

proxies:
  - name: "🇿🇦_1"
    type: vless
    server: "34.35.189.111"
    port: 443
    uuid: "4758aee6-6d1a-4306-b460-2398b5af4e35"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dcox8XXfkOCmKn3kgrloj6wY5o1_0brJOi2mczYmAT4"
      short-id: "5ced03e42cc31aab"
  - name: "🇿🇦_2"
    type: vless
    server: "34.35.186.228"
    port: 443
    uuid: "8d65c8a7-4876-4556-bb6a-feccfb46ee81"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bSN0cv0VMxmYZsNsMkkLndOTHZu74C1htJ2M71QMaVE"
      short-id: "89b3a20484eb43ec"
  - name: "🇿🇦_3"
    type: ss
    server: "20.87.212.24"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "zlHMpI7N5dkZOHdH"
    udp: true
  - name: "🇿🇦_4"
    type: ss
    server: "102.37.156.224"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "aduB9HGxQHjA2SBMRjkHX6"
    udp: true
  - name: "🇿🇦_5"
    type: ss
    server: "102.133.165.160"
    port: 16233
    cipher: "chacha20-ietf-poly1305"
    password: "Xsy8Ox4yOV3xLlpxtjzs3X"
    udp: true
  - name: "🇿🇦_6"
    type: ss
    server: "102.37.156.224"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "aduB9HGxQHjA2SBMRjkHX6"
    udp: true
  - name: "🇿🇦_7"
    type: ss
    server: "102.133.165.160"
    port: 16233
    cipher: "chacha20-ietf-poly1305"
    password: "Xsy8Ox4yOV3xLlpxtjzs3X"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"
      - "Load Balance"

      
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇿🇦_1"
      - "🇿🇦_2"
      - "🇿🇦_3"
      - "🇿🇦_4"
      - "🇿🇦_5"
      - "🇿🇦_6"
      - "🇿🇦_7"


  - name: "Load Balance"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "🇿🇦_1"
      - "🇿🇦_2"
      - "🇿🇦_3"
      - "🇿🇦_4"
      - "🇿🇦_5"
      - "🇿🇦_6"
      - "🇿🇦_7"

rules:
  - MATCH,PROXY
